'use strict';function B(d,a,b,c){d.B.Cb(d.Hb,a,b,c,void 0)}function I(d,a,b,c){d.B.va?B(d,a,b,c):d.B.zg()._OnMessageFromDOM({type:"event",component:d.Hb,handler:a,dispatchOpts:c||null,data:b,responseId:null})}function K(d,a,b){d.B.L(d.Hb,a,b)}function L(d,a){for(const [b,c]of a)K(d,b,c)}function M(d){d.Bc||(d.B.gg(d.$e),d.Bc=!0)}window.Ka=class{constructor(d,a){this.B=d;this.Hb=a;this.Bc=!1;this.$e=()=>this.ib()}Yd(){}ib(){}};function N(d){-1!==d.wb&&(self.clearTimeout(d.wb),d.wb=-1)}
window.Qf=class{constructor(d,a){this.Ed=d;this.Rh=a;this.wb=-1;this.Cc=-Infinity;this.af=()=>{this.wb=-1;this.Cc=Date.now();this.Nb=!0;this.Ed();this.Nb=!1};this.Ie=this.Nb=!1}bd(){this.Nb||(N(this),this.Cc=Date.now())}f(){N(this);this.af=this.Ed=null}};"use strict";function O(d,a){K(d,"get-element",b=>{const c=d.ta.get(b.elementId);return a(c,b)})}
window.Ai=class extends self.Ka{constructor(d,a){super(d,a);this.ta=new Map;this.Dd=!0;L(this,[["create",()=>{throw Error("required override");}],["destroy",b=>{{b=b.elementId;const c=this.ta.get(b);this.Dd&&c.parentElement.removeChild(c);this.ta.delete(b)}}],["set-visible",b=>{this.Dd&&(this.ta.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Dd){var c=this.ta.get(b.elementId);c.style.left=b.left+"px";c.style.top=b.top+"px";c.style.width=b.width+"px";c.style.height=
b.height+"px";b=b.fontSize;null!==b&&(c.style.fontSize=b+"em")}}],["update-state",b=>{this.ta.get(b.elementId);throw Error("required override");}],["focus",b=>this.xd(b)],["set-css-style",b=>{this.ta.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.ta.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.ta.get(b.elementId).removeAttribute(b.name)}]]);O(this,b=>b)}xd(d){var a=this.ta.get(d.elementId);d.focus?a.focus():a.blur()}};"use strict";
{const d=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),a=/android/i.test(navigator.userAgent);let b=0;function c(u){const f=document.createElement("script");f.async=!1;f.type="module";return u.ii?new Promise(r=>{const t="c3_resolve_"+b;++b;self[t]=r;f.textContent=u.ri+`\n\nself["${t}"]();`;document.head.appendChild(f)}):new Promise((r,t)=>{f.onload=r;f.onerror=t;f.src=u;document.head.appendChild(f)})}let l=!1,q=!1;function n(){if(!l){try{new Worker("blob://",{get type(){q=
!0}})}catch(u){}l=!0}return q}let e=new Audio;const h={"audio/webm; codecs=opus":!!e.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!e.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!e.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!e.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!e.canPlayType("audio/mp4"),"audio/mpeg":!!e.canPlayType("audio/mpeg")};e=null;async function g(u){u=await p(u);return(new TextDecoder("utf-8")).decode(u)}
function p(u){return new Promise((f,r)=>{const t=new FileReader;t.onload=y=>f(y.target.result);t.onerror=y=>r(y);t.readAsArrayBuffer(u)})}const z=[];let w=0;window.RealFile=window.File;const v=[],x=new Map,D=new Map;let F=0;const H=[];self.runOnStartup=function(u){if("function"!==typeof u)throw Error("runOnStartup called without a function");H.push(u)};const k=new Set(["cordova","playable-ad","instant-games"]);let m=!1;window.pa=class u{constructor(f){this.va=f.vi;this.Qa=null;this.N="";this.Oc=f.oi;
this.cc={};this.pb=this.bc=null;this.zc=[];this.Qb=this.T=this.ub=null;this.tb=-1;this.ai=()=>this.Yg();this.sb=[];this.A=f.bf;this.Ob="file"===location.protocol.substr(0,4);!this.va||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&n()||(this.va=!1);if("playable-ad"===this.A||"instant-games"===this.A)this.va=!1;if("cordova"===this.A&&this.va)if(a){const r=/Chrome\/(\d+)/i.exec(navigator.userAgent);r&&90<=parseInt(r[1],10)||(this.va=!1)}else this.va=!1;this.Ec=this.Ea=null;"html5"!==
this.A&&"playable-ad"!==this.A||!this.Ob||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");"html5"!==this.A||window.isSecureContext||console.warn("[Construct 3] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.L("runtime","cordova-fetch-local-file",r=>this.Hg(r));this.L("runtime",
"create-job-worker",()=>this.Ig());"cordova"===this.A?document.addEventListener("deviceready",()=>this.ve(f)):this.ve(f)}f(){this.jd();this.Qa&&(this.Qa=this.Qa.onmessage=null);this.bc&&(this.bc.terminate(),this.bc=null);this.pb&&(this.pb.f(),this.pb=null);this.T&&(this.T.parentElement.removeChild(this.T),this.T=null)}Lf(){return d&&"cordova"===this.A}$c(){const f=navigator.userAgent;return d&&k.has(this.A)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(f)}Jf(){return a}fe(){return a&&k.has(this.A)}async ve(f){"macos-wkwebview"===
this.A&&this.Bd({type:"ready"});if("playable-ad"===this.A){this.Ea=self.c3_base64files;this.Ec={};await this.ng();for(let t=0,y=f.xb.length;t<y;++t){var r=f.xb[t].toLowerCase();this.Ec.hasOwnProperty(r)?f.xb[t]={ii:!0,ri:this.Ec[r]}:this.Ea.hasOwnProperty(r)&&(f.xb[t]=URL.createObjectURL(this.Ea[r]))}}f.bi?this.N=f.bi:(r=location.origin,this.N=("null"===r?"file:///":r)+location.pathname,r=this.N.lastIndexOf("/"),-1!==r&&(this.N=this.N.substr(0,r+1)));f.yi&&(this.cc=f.yi);r=new MessageChannel;this.Qa=
r.port1;this.Qa.onmessage=t=>this._OnMessageFromRuntime(t.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(t=>this.Ug(t));this.Qb=new self.Mf(this);await P(this.Qb);"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.va?await this.Cg(f,r.port2):await this.Bg(f,r.port2)}md(f){f=this.cc.hasOwnProperty(f)?this.cc[f]:f.endsWith("/workermain.js")&&this.cc.hasOwnProperty("workermain.js")?
this.cc["workermain.js"]:"playable-ad"===this.A&&this.Ea.hasOwnProperty(f.toLowerCase())?this.Ea[f.toLowerCase()]:f;f instanceof Blob&&(f=URL.createObjectURL(f));return f}async Tc(f,r,t){if(f.startsWith("blob:"))return new Worker(f,t);if("cordova"===this.A&&this.Ob)return f=await this.dc(t.hi?f:this.Oc+f),new Worker(URL.createObjectURL(new Blob([f],{type:"application/javascript"})),t);f=new URL(f,r);if(location.origin!==f.origin){f=await fetch(f);if(!f.ok)throw Error("failed to fetch worker script");
f=await f.blob();return new Worker(URL.createObjectURL(f),t)}return new Worker(f,t)}Oa(){return Math.max(window.innerWidth,1)}za(){return Math.max(window.innerHeight,1)}se(f){var r=this.Qb;return{baseUrl:this.N,windowInnerWidth:this.Oa(),windowInnerHeight:this.za(),devicePixelRatio:window.devicePixelRatio,isFullscreen:u.Ab(),projectData:f.Mi,previewImageBlobs:window.cr_previewImageBlobs||this.Ea,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,
swClientId:window.Hi||"",exportType:f.bf,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.Li,jobScheduler:{inputPort:r.Ld,outputPort:r.Rd,maxNumWorkers:r.Xh},supportedAudioFormats:h,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Oc+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.Oc+"opus.wasm.wasm",isFileProtocol:this.Ob,isiOSCordova:this.Lf(),isiOSWebView:this.$c(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Cg(f,r){var t=this.md(f.xi);this.bc=
await this.Tc(t,this.N,{type:"module",name:"Runtime",hi:!0});this.T=document.createElement("canvas");this.T.style.display="none";t=this.T.transferControlToOffscreen();document.body.appendChild(this.T);window.c3canvas=this.T;let y=f.Xd||[],E=f.xb;y=await Promise.all(y.map(A=>this.jb(A)));E=await Promise.all(E.map(A=>this.jb(A)));if("cordova"===this.A)for(let A=0,C=f.Rc.length;A<C;++A){const G=f.Rc[A],J=G[0];if(J===f.Vd||"scriptsInEvents.js"===J||J.endsWith("/scriptsInEvents.js"))G[1]=await this.jb(J)}this.bc.postMessage(Object.assign(this.se(f),
{type:"init-runtime",isInWorker:!0,messagePort:r,canvas:t,workerDependencyScripts:y,engineScripts:E,projectScripts:f.Rc,mainProjectScript:f.Vd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[r,t,...Q(this.Qb)]);this.zc=v.map(A=>new A(this));this.qe();self.c3_callFunction=(A,C)=>this.ub.Dg(A,C);"preview"===this.A&&(self.goToLastErrorScript=()=>this.Cb("runtime","go-to-last-error-script"))}async Bg(f,r){this.T=document.createElement("canvas");this.T.style.display="none";document.body.appendChild(this.T);
window.c3canvas=this.T;this.zc=v.map(A=>new A(this));this.qe();var t=f.xb.map(A=>"string"===typeof A?(new URL(A,this.N)).toString():A);Array.isArray(f.Xd)&&t.unshift(...f.Xd);t=await Promise.all(t.map(A=>this.jb(A)));await Promise.all(t.map(A=>c(A)));t=self.C3_ProjectScriptsStatus;const y=f.Vd,E=f.Rc;for(let [A,C]of E)if(C||(C=A),A===y)try{C=await this.jb(C),await c(C),"preview"!==this.A||t[A]||this.De(A,"main script did not run to completion")}catch(G){this.De(A,G)}else if("scriptsInEvents.js"===
A||A.endsWith("/scriptsInEvents.js"))C=await this.jb(C),await c(C);"preview"===this.A&&"object"!==typeof self.zi.Bi?(this.sc(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(f=Object.assign(this.se(f),{isInWorker:!1,messagePort:r,canvas:this.T,runOnStartupFunctions:H}),this.xe(),this.pb=self.C3_CreateRuntime(f),await self.C3_InitRuntime(this.pb,
f))}De(f,r){this.sc();console.error(`[Preview] Failed to load project main script (${f}): `,r);alert(`Failed to load project main script (${f}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}xe(){this.sc()}sc(){const f=window.ci;f&&(f.parentElement.removeChild(f),window.ci=null)}async Ig(){const f=await R(this.Qb);return{outputPort:f,transferables:[f]}}zg(){if(this.va)throw Error("not available in worker mode");return this.pb}Cb(f,r,t,y,E){this.Qa.postMessage({type:"event",
component:f,handler:r,dispatchOpts:y||null,data:t,responseId:null},E)}he(f,r,t,y,E){const A=F++,C=new Promise((G,J)=>{D.set(A,{resolve:G,reject:J})});this.Qa.postMessage({type:"event",component:f,handler:r,dispatchOpts:y||null,data:t,responseId:A},E);return C}["_OnMessageFromRuntime"](f){const r=f.type;if("event"===r)return this.Ng(f);if("result"===r)this.bh(f);else if("runtime-ready"===r)this.dh();else if("alert-error"===r)this.sc(),alert(f.message);else if("creating-runtime"===r)this.xe();else throw Error(`unknown message '${r}'`);
}Ng(f){const r=f.component,t=f.handler,y=f.data,E=f.responseId;if(f=x.get(r))if(f=f.get(t)){var A=null;try{A=f(y)}catch(C){console.error(`Exception in '${r}' handler '${t}':`,C);null!==E&&this.rc(E,!1,""+C);return}if(null===E)return A;A&&A.then?A.then(C=>this.rc(E,!0,C)).catch(C=>{console.error(`Rejection from '${r}' handler '${t}':`,C);this.rc(E,!1,""+C)}):this.rc(E,!0,A)}else console.warn(`[DOM] No handler '${t}' for component '${r}'`);else console.warn(`[DOM] No event handlers for component '${r}'`)}rc(f,
r,t){let y;t&&t.transferables&&(y=t.transferables);this.Qa.postMessage({type:"result",responseId:f,isOk:r,result:t},y)}bh(f){const r=f.responseId,t=f.isOk;f=f.result;const y=D.get(r);t?y.resolve(f):y.reject(f);D.delete(r)}L(f,r,t){let y=x.get(f);y||(y=new Map,x.set(f,y));if(y.has(r))throw Error(`[DOM] Component '${f}' already has handler '${r}'`);y.set(r,t)}static Ta(f){if(v.includes(f))throw Error("DOM handler already added");v.push(f)}qe(){for(const f of this.zc)if("runtime"===f.Hb){this.ub=f;return}throw Error("cannot find runtime DOM handler");
}Ug(f){this.Cb("debugger","message",f)}dh(){for(const f of this.zc)f.Yd()}static Ab(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||m)}static tc(f){m=!!f}gg(f){this.sb.push(f);this.Ad()}rh(f){f=this.sb.indexOf(f);if(-1===f)throw Error("invalid callback");this.sb.splice(f,1);this.sb.length||this.jd()}Ad(){-1===this.tb&&this.sb.length&&(this.tb=requestAnimationFrame(this.ai))}jd(){-1!==this.tb&&(cancelAnimationFrame(this.tb),this.tb=-1)}Yg(){this.tb=
-1;for(const f of this.sb)f();this.Ad()}Za(f){this.ub.Za(f)}hb(f){this.ub.hb(f)}zd(){this.ub.zd()}mc(f){this.ub.mc(f)}Kf(){return!!h["audio/webm; codecs=opus"]}async Ph(f){f=await this.he("runtime","opus-decode",{arrayBuffer:f},null,[f]);return new Float32Array(f)}If(f){return/^(?:[a-z\-]+:)?\/\//.test(f)||"data:"===f.substr(0,5)||"blob:"===f.substr(0,5)}ge(f){return!this.If(f)}async jb(f){return"cordova"===this.A&&(f.startsWith("file:")||this.Ob&&this.ge(f))?(f.startsWith(this.N)&&(f=f.substr(this.N.length)),
f=await this.dc(f),URL.createObjectURL(new Blob([f],{type:"application/javascript"}))):f}async Hg(f){const r=f.filename;switch(f.as){case "text":return await this.zf(r);case "buffer":return await this.dc(r);default:throw Error("unsupported type");}}be(f){const r=window.cordova.file.applicationDirectory+"www/"+f.toLowerCase();return new Promise((t,y)=>{window.resolveLocalFileSystemURL(r,E=>{E.file(t,y)},y)})}async zf(f){f=await this.be(f);return await g(f)}kd(){if(z.length&&!(8<=w)){w++;var f=z.shift();
this.og(f.filename,f.si,f.fi)}}dc(f){return new Promise((r,t)=>{z.push({filename:f,si:y=>{w--;this.kd();r(y)},fi:y=>{w--;this.kd();t(y)}});this.kd()})}async og(f,r,t){try{const y=await this.be(f),E=await p(y);r(E)}catch(y){t(y)}}Bd(f){if("windows-webview2"===this.A)window.chrome.webview.postMessage(JSON.stringify(f));else if("macos-wkwebview"===this.A)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(f));else throw Error("cannot send wrapper message");}async ng(){const f=[];for(const [r,
t]of Object.entries(this.Ea))f.push(this.mg(r,t));await Promise.all(f)}async mg(f,r){if("object"===typeof r)this.Ea[f]=new Blob([r.str],{type:r.type}),this.Ec[f]=r.str;else{let t=await this.xg(r);t||(t=this.sg(r));this.Ea[f]=t}}async xg(f){try{return await (await fetch(f)).blob()}catch(r){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
r),null}}sg(f){f=this.lh(f);return this.kg(f.data,f.ji)}lh(f){var r=f.indexOf(",");if(0>r)throw new URIError("expected comma in data: uri");var t=f.substring(r+1);r=f.substring(5,r).split(";");f=r[0]||"";const y=r[2];t="base64"===r[1]||"base64"===y?atob(t):decodeURIComponent(t);return{ji:f,data:t}}kg(f,r){var t=f.length;let y=t>>2,E=new Uint8Array(t),A=new Uint32Array(E.buffer,0,y),C,G;for(G=C=0;C<y;++C)A[C]=f.charCodeAt(G++)|f.charCodeAt(G++)<<8|f.charCodeAt(G++)<<16|f.charCodeAt(G++)<<24;for(t&=
3;t--;)E[G]=f.charCodeAt(G),++G;return new Blob([E],{type:r})}}}"use strict";
{const d=self.pa;function a(k){return k.sourceCapabilities&&k.sourceCapabilities.firesTouchEvents||k.originalEvent&&k.originalEvent.sourceCapabilities&&k.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),c={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},l={dispatchUserScriptEvent:!0},q={dispatchRuntimeEvent:!0};function n(k){return new Promise((m,u)=>{const f=document.createElement("link");f.onload=()=>m(f);f.onerror=r=>u(r);f.rel=
"stylesheet";f.href=k;document.head.appendChild(f)})}function e(k){return new Promise((m,u)=>{const f=new Image;f.onload=()=>m(f);f.onerror=r=>u(r);f.src=k})}async function h(k){k=URL.createObjectURL(k);try{return await e(k)}finally{URL.revokeObjectURL(k)}}function g(k){return new Promise((m,u)=>{let f=new FileReader;f.onload=r=>m(r.target.result);f.onerror=r=>u(r);f.readAsText(k)})}async function p(k,m,u){if(!/firefox/i.test(navigator.userAgent))return await h(k);var f=await g(k);f=(new DOMParser).parseFromString(f,
"image/svg+xml");const r=f.documentElement;if(r.hasAttribute("width")&&r.hasAttribute("height")){const t=r.getAttribute("width"),y=r.getAttribute("height");if(!t.includes("%")&&!y.includes("%"))return await h(k)}r.setAttribute("width",m+"px");r.setAttribute("height",u+"px");f=(new XMLSerializer).serializeToString(f);k=new Blob([f],{type:"image/svg+xml"});return await h(k)}function z(k){do{if(k.parentNode&&k.hasAttribute("contenteditable"))return!0;k=k.parentNode}while(k);return!1}const w=new Set(["input",
"textarea","datalist","select"]),v=new Set(["canvas","body","html"]);function x(k){v.has(k.target.tagName.toLowerCase())&&k.preventDefault()}function D(k){(k.metaKey||k.ctrlKey)&&k.preventDefault()}self.C3_GetSvgImageSize=async function(k){k=await h(k);if(0<k.width&&0<k.height)return[k.width,k.height];{k.style.position="absolute";k.style.left="0px";k.style.top="0px";k.style.visibility="hidden";document.body.appendChild(k);const m=k.getBoundingClientRect();document.body.removeChild(k);return[m.width,
m.height]}};self.C3_RasterSvgImageBlob=async function(k,m,u,f,r){k=await p(k,m,u);const t=document.createElement("canvas");t.width=f;t.height=r;t.getContext("2d").drawImage(k,0,0,m,u);return t};let F=!1;document.addEventListener("pause",()=>F=!0);document.addEventListener("resume",()=>F=!1);function H(){try{return window.parent&&window.parent.document.hasFocus()}catch(k){return!1}}d.Ta(class extends self.Ka{constructor(k){super(k,"runtime");this.Ne=!0;this.vb=-1;this.Td="any";this.Ee=this.Fe=!1;this.ob=
this.Yb=this.bb=null;this.Kc=this.Jc=0;this.Re=k.Oa();this.Dc=k.za();this.$b=0;k.L("canvas","update-size",f=>this.ih(f));k.L("runtime","invoke-download",f=>this.Sg(f));k.L("runtime","raster-svg-image",f=>this.Zg(f));k.L("runtime","get-svg-image-size",f=>this.Pg(f));k.L("runtime","set-target-orientation",f=>this.eh(f));k.L("runtime","register-sw",()=>this.ah());k.L("runtime","post-to-debugger",f=>this.ze(f));k.L("runtime","go-to-script",f=>this.ze(f));k.L("runtime","before-start-ticking",()=>this.Gg());
k.L("runtime","debug-highlight",f=>this.Jg(f));k.L("runtime","enable-device-orientation",()=>this.jg());k.L("runtime","enable-device-motion",()=>this.ig());k.L("runtime","add-stylesheet",f=>this.Fg(f));k.L("runtime","alert",f=>this.qd(f));k.L("runtime","hide-cordova-splash",()=>this.Qg());const m=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",f=>{const r=f.target;m.has(r.tagName.toLowerCase())||z(r)||f.preventDefault()});const u=k.T;window.addEventListener("selectstart",
x);window.addEventListener("gesturehold",x);u.addEventListener("selectstart",x);u.addEventListener("gesturehold",x);window.addEventListener("touchstart",x,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",x,{passive:!1}),u.addEventListener("pointerdown",x)):u.addEventListener("touchstart",x);this.Vb=0;window.addEventListener("mousedown",f=>{1===f.button&&f.preventDefault()});window.addEventListener("mousewheel",D,{passive:!1});window.addEventListener("wheel",D,
{passive:!1});window.addEventListener("resize",()=>this.jh());window.addEventListener("fullscreenchange",()=>this.Db());window.addEventListener("webkitfullscreenchange",()=>this.Db());window.addEventListener("mozfullscreenchange",()=>this.Db());window.addEventListener("fullscreenerror",f=>this.td(f));window.addEventListener("webkitfullscreenerror",f=>this.td(f));window.addEventListener("mozfullscreenerror",f=>this.td(f));k.$c()&&window.addEventListener("focusout",()=>{{const t=document.activeElement;
if(t){var f=t.tagName.toLowerCase();var r=new Set("email number password search tel text url".split(" "));f="textarea"===f?!0:"input"===f?r.has(t.type.toLowerCase()||"text"):z(t)}else f=!1}f||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=f=>this.kh(f);this.qb=new Set;this.Fc=new WeakSet;this.Pa=!1}Gg(){"cordova"===this.B.A?(document.addEventListener("pause",()=>this.yd(!0)),document.addEventListener("resume",()=>this.yd(!1))):document.addEventListener("visibilitychange",()=>this.yd(document.hidden));
return{isSuspended:!(!document.hidden&&!F)}}Yd(){window.addEventListener("focus",()=>this.Fb("window-focus"));window.addEventListener("blur",()=>{this.Fb("window-blur",{parentHasFocus:H()});this.Vb=0});window.addEventListener("focusin",m=>{m=m.target;(w.has(m.tagName.toLowerCase())||z(m))&&this.Fb("keyboard-blur")});window.addEventListener("keydown",m=>this.ye("keydown",m));window.addEventListener("keyup",m=>this.ye("keyup",m));window.addEventListener("dblclick",m=>this.vd("dblclick",m,c));window.addEventListener("wheel",
m=>this.Wg(m));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",m=>{this.nd(m);this.Eb("pointerdown",m)}),this.B.va&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.Yb=new self.Qf(()=>this.vg(),5),this.Yb.Ie=!0,window.addEventListener("pointerrawupdate",m=>this.Xg(m))):window.addEventListener("pointermove",m=>this.Eb("pointermove",m)),window.addEventListener("pointerup",m=>this.Eb("pointerup",m)),window.addEventListener("pointercancel",m=>this.Eb("pointercancel",
m))):(window.addEventListener("mousedown",m=>{this.nd(m);this.wd("pointerdown",m)}),window.addEventListener("mousemove",m=>this.wd("pointermove",m)),window.addEventListener("mouseup",m=>this.wd("pointerup",m)),window.addEventListener("touchstart",m=>{this.nd(m);this.qc("pointerdown",m)}),window.addEventListener("touchmove",m=>this.qc("pointermove",m)),window.addEventListener("touchend",m=>this.qc("pointerup",m)),window.addEventListener("touchcancel",m=>this.qc("pointercancel",m)));const k=()=>this.zd();
window.addEventListener("pointerup",k,!0);window.addEventListener("touchend",k,!0);window.addEventListener("click",k,!0);window.addEventListener("keydown",k,!0);window.addEventListener("gamepadconnected",k,!0);this.B.Jf()&&!this.B.fe()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{this.rd(this.za(),navigator.virtualKeyboard.boundingRect.height)}))}rd(k,m){document.body.style.transform="";if(0<m){var u=document.activeElement;
u&&(u=u.getBoundingClientRect(),k=(u.top+u.bottom)/2-(k-m)/2,k>m&&(k=m),0>k&&(k=0),0<k&&(document.body.style.transform=`translateY(${-k}px)`))}}Fb(k,m){B(this,k,m||null,q)}Oa(){return this.B.Oa()}za(){return this.B.za()}jh(){const k=this.Oa(),m=this.za();if(this.B.fe()){if(this.Re===k&&m<this.Dc){this.$b=this.Dc-m;this.rd(this.Dc,this.$b);return}0<this.$b&&(this.$b=0,this.rd(m,this.$b));this.Re=k;this.Dc=m}this.Fb("window-resize",{innerWidth:k,innerHeight:m,devicePixelRatio:window.devicePixelRatio,
isFullscreen:d.Ab()});this.B.$c()&&(-1!==this.vb&&clearTimeout(this.vb),this.Ae(k,m,0))}sh(k,m,u){-1!==this.vb&&clearTimeout(this.vb);this.vb=setTimeout(()=>this.Ae(k,m,u),48)}Ae(k,m,u){const f=this.Oa(),r=this.za();this.vb=-1;f!=k||r!=m?this.Fb("window-resize",{innerWidth:f,innerHeight:r,devicePixelRatio:window.devicePixelRatio,isFullscreen:d.Ab()}):10>u&&this.sh(f,r,u+1)}eh(k){this.Td=k.targetOrientation}Lh(){const k=this.Td;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(k).catch(m=>
console.warn("[Construct 3] Failed to lock orientation: ",m));else try{let m=!1;screen.lockOrientation?m=screen.lockOrientation(k):screen.webkitLockOrientation?m=screen.webkitLockOrientation(k):screen.mozLockOrientation?m=screen.mozLockOrientation(k):screen.msLockOrientation&&(m=screen.msLockOrientation(k));m||console.warn("[Construct 3] Failed to lock orientation")}catch(m){console.warn("[Construct 3] Failed to lock orientation: ",m)}}Db(){const k=d.Ab();k&&"any"!==this.Td&&this.Lh();B(this,"fullscreenchange",
{isFullscreen:k,innerWidth:this.Oa(),innerHeight:this.za()})}td(k){console.warn("[Construct 3] Fullscreen request failed: ",k);B(this,"fullscreenerror",{isFullscreen:d.Ab(),innerWidth:this.Oa(),innerHeight:this.za()})}yd(k){k?this.B.jd():this.B.Ad();B(this,"visibilitychange",{hidden:k})}ye(k,m){"Backspace"===m.key&&x(m);const u=b.get(m.code)||m.code;I(this,k,{code:u,key:m.key,which:m.which,repeat:m.repeat,altKey:m.altKey,ctrlKey:m.ctrlKey,metaKey:m.metaKey,shiftKey:m.shiftKey,timeStamp:m.timeStamp},
c)}Wg(k){B(this,"wheel",{clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,deltaX:k.deltaX,deltaY:k.deltaY,deltaZ:k.deltaZ,deltaMode:k.deltaMode,timeStamp:k.timeStamp},c)}vd(k,m,u){a(m)||I(this,k,{button:m.button,buttons:m.buttons,clientX:m.clientX,clientY:m.clientY,pageX:m.pageX,pageY:m.pageY,movementX:m.movementX||0,movementY:m.movementY||0,timeStamp:m.timeStamp},u)}wd(k,m){if(!a(m)){var u=this.Vb;"pointerdown"===k&&0!==u?k="pointermove":"pointerup"===k&&0!==m.buttons&&(k="pointermove");
I(this,k,{pointerId:1,pointerType:"mouse",button:m.button,buttons:m.buttons,lastButtons:u,clientX:m.clientX,clientY:m.clientY,pageX:m.pageX,pageY:m.pageY,movementX:m.movementX||0,movementY:m.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:m.timeStamp},c);this.Vb=m.buttons;this.vd(m.type,m,l)}}Eb(k,m){this.Yb&&"pointermove"!==k&&this.Yb.bd();var u=0;"mouse"===m.pointerType&&(u=this.Vb);I(this,k,{pointerId:m.pointerId,pointerType:m.pointerType,button:m.button,
buttons:m.buttons,lastButtons:u,clientX:m.clientX,clientY:m.clientY,pageX:m.pageX,pageY:m.pageY,movementX:(m.movementX||0)+this.Jc,movementY:(m.movementY||0)+this.Kc,width:m.width||0,height:m.height||0,pressure:m.pressure||0,tangentialPressure:m.tangentialPressure||0,tiltX:m.tiltX||0,tiltY:m.tiltY||0,twist:m.twist||0,timeStamp:m.timeStamp},c);this.Kc=this.Jc=0;"mouse"===m.pointerType&&(u="mousemove","pointerdown"===k?u="mousedown":"pointerup"===k&&(u="mouseup"),this.vd(u,m,l),this.Vb=m.buttons)}Xg(k){this.ob&&
(this.Jc+=this.ob.movementX||0,this.Kc+=this.ob.movementY||0);this.ob=k;k=this.Yb;if(-1===k.wb){var m=Date.now(),u=m-k.Cc,f=k.Rh;u>=f&&k.Ie?(k.Cc=m,k.Nb=!0,k.Ed(),k.Nb=!1):k.wb=self.setTimeout(k.af,Math.max(f-u,4))}}vg(){this.Eb("pointermove",this.ob);this.ob=null}qc(k,m){for(let u=0,f=m.changedTouches.length;u<f;++u){const r=m.changedTouches[u];I(this,k,{pointerId:r.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:r.clientX,clientY:r.clientY,pageX:r.pageX,pageY:r.pageY,movementX:m.movementX||
0,movementY:m.movementY||0,width:2*(r.radiusX||r.webkitRadiusX||0),height:2*(r.radiusY||r.webkitRadiusY||0),pressure:r.force||r.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:r.rotationAngle||0,timeStamp:m.timeStamp},c)}}nd(k){window!==window.top&&window.focus();this.we(k.target)&&document.activeElement&&!this.we(document.activeElement)&&document.activeElement.blur()}we(k){return!k||k===document||k===window||k===document.body||"canvas"===k.tagName.toLowerCase()}jg(){this.Fe||(this.Fe=!0,
window.addEventListener("deviceorientation",k=>this.Lg(k)),window.addEventListener("deviceorientationabsolute",k=>this.Mg(k)))}ig(){this.Ee||(this.Ee=!0,window.addEventListener("devicemotion",k=>this.Kg(k)))}Lg(k){B(this,"deviceorientation",{absolute:!!k.absolute,alpha:k.alpha||0,beta:k.beta||0,gamma:k.gamma||0,timeStamp:k.timeStamp,webkitCompassHeading:k.webkitCompassHeading,webkitCompassAccuracy:k.webkitCompassAccuracy},c)}Mg(k){B(this,"deviceorientationabsolute",{absolute:!!k.absolute,alpha:k.alpha||
0,beta:k.beta||0,gamma:k.gamma||0,timeStamp:k.timeStamp},c)}Kg(k){let m=null;var u=k.acceleration;u&&(m={x:u.x||0,y:u.y||0,z:u.z||0});u=null;var f=k.accelerationIncludingGravity;f&&(u={x:f.x||0,y:f.y||0,z:f.z||0});f=null;const r=k.rotationRate;r&&(f={alpha:r.alpha||0,beta:r.beta||0,gamma:r.gamma||0});B(this,"devicemotion",{acceleration:m,accelerationIncludingGravity:u,rotationRate:f,interval:k.interval,timeStamp:k.timeStamp},c)}ih(k){const m=this.B.T;m.style.width=k.styleWidth+"px";m.style.height=
k.styleHeight+"px";m.style.marginLeft=k.marginLeft+"px";m.style.marginTop=k.marginTop+"px";this.Ne&&(m.style.display="",this.Ne=!1)}Sg(k){const m=k.url;k=k.filename;const u=document.createElement("a"),f=document.body;u.textContent=k;u.href=m;u.download=k;f.appendChild(u);u.click();f.removeChild(u)}async Zg(k){var m=k.imageBitmapOpts;k=await self.C3_RasterSvgImageBlob(k.blob,k.imageWidth,k.imageHeight,k.surfaceWidth,k.surfaceHeight);m=m?await createImageBitmap(k,m):await createImageBitmap(k);return{imageBitmap:m,
transferables:[m]}}async Pg(k){return await self.C3_GetSvgImageSize(k.blob)}async Fg(k){await n(k.url)}zd(){var k=[...this.qb];this.qb.clear();if(!this.Pa)for(const m of k)(k=m.play())&&k.catch(()=>{this.Fc.has(m)||this.qb.add(m)})}Za(k){if("function"!==typeof k.play)throw Error("missing play function");this.Fc.delete(k);let m;try{m=k.play()}catch(u){this.qb.add(k);return}m&&m.catch(()=>{this.Fc.has(k)||this.qb.add(k)})}hb(k){this.qb.delete(k);this.Fc.add(k)}mc(k){this.Pa=!!k}Qg(){navigator.splashscreen&&
navigator.splashscreen.hide&&navigator.splashscreen.hide()}Jg(k){if(k.show){this.bb||(this.bb=document.createElement("div"),this.bb.id="inspectOutline",document.body.appendChild(this.bb));var m=this.bb;m.style.display="";m.style.left=k.left-1+"px";m.style.top=k.top-1+"px";m.style.width=k.width+2+"px";m.style.height=k.height+2+"px";m.textContent=k.name}else this.bb&&(this.bb.style.display="none")}ah(){window.C3_RegisterSW&&window.C3_RegisterSW()}ze(k){window.c3_postToMessagePort&&(k.from="runtime",
window.c3_postToMessagePort(k))}Dg(k,m){return this.B.he(this.Hb,"js-invoke-function",{name:k,params:m},void 0,void 0)}qd(k){alert(k.message)}kh(k){"entered-fullscreen"===k?(d.tc(!0),this.Db()):"exited-fullscreen"===k?(d.tc(!1),this.Db()):console.warn("Unknown wrapper message: ",k)}})}"use strict";
async function P(d){if(d.Qh)throw Error("already initialised");d.Qh=!0;var a=d.Nc.md("dispatchworker.js");d.Gd=await d.Nc.Tc(a,d.N,{name:"DispatchWorker"});a=new MessageChannel;d.Ld=a.port1;d.Gd.postMessage({type:"_init","in-port":a.port2},[a.port2]);d.Rd=await R(d)}function Q(d){return[d.Ld,d.Rd]}
async function R(d){const a=d.Oe.length;var b=d.Nc.md("jobworker.js");b=await d.Nc.Tc(b,d.N,{name:"JobWorker"+a});const c=new MessageChannel,l=new MessageChannel;d.Gd.postMessage({type:"_addJobWorker",port:c.port1},[c.port1]);b.postMessage({type:"init",number:a,"dispatch-port":c.port2,"output-port":l.port2},[c.port2,l.port2]);d.Oe.push(b);return l.port1}
self.Mf=class{constructor(d){this.Nc=d;this.N=d.N;this.N="preview"===d.A?this.N+"workers/":this.N+d.Oc;this.Xh=Math.min(navigator.hardwareConcurrency||2,16);this.Gd=null;this.Oe=[];this.Rd=this.Ld=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.pa({vi:!0,xi:"workermain.js",xb:["scripts/c3runtime.js"],Rc:[],Vd:"",oi:"scripts/",Xd:[],bf:"html5"}));"use strict";
async function S(d,a){a=a.type;let b=!0;0===a?b=await T():1===a&&(b=await U());B(d,"permission-result",{type:a,result:b})}async function T(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(d){return console.warn("[Touch] Failed to request orientation permission: ",d),!1}}
async function U(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(d){return console.warn("[Touch] Failed to request motion permission: ",d),!1}}self.pa.Ta(class extends self.Ka{constructor(d){super(d,"touch");K(this,"request-permission",a=>S(this,a))}});"use strict";
function V(d){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>B(d,"sw-message",a.data))}
function W(d){d=d.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(d).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(d):screen.webkitLockOrientation?a=screen.webkitLockOrientation(d):screen.mozLockOrientation?a=screen.mozLockOrientation(d):screen.msLockOrientation&&(a=screen.msLockOrientation(d));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",
a)}}
self.pa.Ta(class extends self.Ka{constructor(d){super(d,"browser");this.A="";L(this,[["get-initial-state",a=>this.ud(a)],["ready-for-sw-messages",()=>V(this)],["alert",a=>this.qd(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.xd(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>W(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?
screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===b)window.history.forward();else if("reload"===b)location.reload();else if("url"===
b){b=a.url;const c=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):"preview"===a||"windows-webview2"===a?window.open(b,"_blank"):this.Gi||(2===c?window.top.location=b:1===c?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,a))}],["request-fullscreen",a=>{if("windows-webview2"===this.A||"macos-wkwebview"===this.A)self.pa.tc(!0),
this.B.Bd({type:"set-fullscreen",fullscreen:!0});else{const b={navigationUI:"auto"};a=a.navUI;1===a?b.navigationUI="hide":2===a&&(b.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(b):a.mozRequestFullScreen?a.mozRequestFullScreen(b):a.msRequestFullscreen?a.msRequestFullscreen(b):a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}}],["exit-fullscreen",
()=>{"windows-webview2"===this.A||"macos-wkwebview"===this.A?(self.pa.tc(!1),this.B.Bd({type:"set-fullscreen",fullscreen:!1})):document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{B(this,"online-state",{isOnline:!0})});window.addEventListener("offline",
()=>{B(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{B(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{B(this,"backbutton")})}ud(d){this.A=d.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,
isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}qd(d){alert(d.message)}xd(d){d=d.isFocus;if("nwjs"===this.A){const a="nwjs"===this.A?nw.Window.get():null;d?a.focus():a.blur()}else d?window.focus():window.blur()}});"use strict";
{function d(){const a=self.RealFile||self.File;return"function"===typeof navigator.canShare&&navigator.canShare({files:[new a(["test file"],"test.txt",{})]})}self.pa.Ta(class extends self.Ka{constructor(a){super(a,"share");a=!!this.ue();this.Uh=(this.Wh="function"===typeof navigator.share)||a;this.Sh=(this.Vh=d())||a;L(this,[["init",()=>this.Rg()],["share",b=>this.fh(b)],["request-rate",b=>this.$g(b)],["request-store",b=>this.gh(b)]])}Rg(){return{isSupported:this.Uh,isFilesSupported:this.Sh}}ue(){return window.plugins&&
window.plugins.socialsharing}te(){return window.cordova&&window.cordova.plugins&&window.cordova.plugins.RateApp}async fh(a){var b=a.text;const c=a.title,l=a.url;a=a.files.slice(0);const q=0<a.length,n=this.ue();if(n){const h={};b&&(h.message=b);c&&(h.subject=c);l&&(h.url=l);if(q){b=0;for(var e of a)b+=e.size;try{const g=await this.pg(Math.floor(1.25*b));h.files=await Promise.all(a.map(p=>this.qg(p,g)))}catch(g){console.log("[Share plugin] Share failed: ",g);B(this,"share-failed");return}}n.shareWithOptions(h,
()=>{B(this,"share-completed")},g=>{console.log("[Share plugin] Share failed: ",g);B(this,"share-failed")})}else{e={};b&&(e.text=b);c&&(e.title=c);l&&(e.url=l);q&&(e.files=a);try{await navigator.share(e),B(this,"share-completed")}catch(h){console.log("[Share plugin] Share failed: ",h),B(this,"share-failed")}}}$g(a){const b=a.body,c=a.confirm,l=a.cancel;a=a.appID;const q=this.te();q&&q.Rate(b,c,l,a)}gh(a){a=a.appID;const b=this.te();b&&b.Store(a)}pg(a){return new Promise((b,c)=>{window.requestFileSystem(window.TEMPORARY,
a,l=>b(l.root),c)})}qg(a,b){return new Promise((c,l)=>{b.getFile(a.name,{create:!0,exclusive:!1},q=>{const n=q.toURL();q.createWriter(e=>{e.onwriteend=()=>c(n);e.onerror=l;e.write(a)})},l)})}})}"use strict";
{const d={};let a=null,b=null;const c={banner:"ca-app-pub-3940256099942544/2934735716",interstitial:"ca-app-pub-3940256099942544/4411468910",rewarded:"ca-app-pub-3940256099942544/1712485313",rewardedInterstitial:"ca-app-pub-3940256099942544/6978759866"};let l=!1;function q(e,h){d[e]=h;self.admob.configRequest(d)}async function n(){if("android"===self.cordova.platformId)return self.Zd(self.device.uuid).toUpperCase();if("ios"===self.cordova.platformId){const e=await self.cordova.plugins.idfa.gi();if(!e.ti)return l=
!0,self.Zd(e.Ki).toUpperCase()}}self.Ua={D:function(e,h){e(null,h)},u:function(e,h){e(h,null)},la:async function(e,h){h="undefined"!==typeof h?h:a.debug;return b?b:b=new Promise(g=>{document.addEventListener("deviceready",async()=>{try{const p=setTimeout(()=>{g(!1);e("failure to initialize",null)},2E3);await self.admob.start();clearTimeout(p);if(h){const z=await n();q("testDeviceIds",[z])}g(!0)}catch(p){g(!1),e("Initialization failure",null)}})})},hd:q,Wf:function(e,h,g,p,z,w,v){a||(a={id:e,mi:h,
ki:g,pi:p,Ni:z,debug:w,di:v},Object.freeze(a))},Gf:function(){return!!a},ec:function(e,h){if("android"===self.cordova.platformId)return e;if("ios"===self.cordova.platformId){const g=!!c[h];return a.debug&&!l&&g?(console.log("[C3 advert]","USING TEST AD UNITS"),c[h]):e}},get Va(){return a},get cg(){return n()}}}"use strict";
{const d=self.Ua,a=d.D,b=d.u,c={get U(){return self.admob.Events.bannerLoad},get V(){return self.admob.Events.bannerLoadFail}};class l{constructor(n,e,h,g){if(!n)return b(g,"Unit ID not specified");if(!e)return b(g,"Ad size not specified");if(!h)return b(g,"Ad position not specified");this.$a=n;this.$h=h;this.Ia="";switch(e){case "portrait":this.Ia=5;break;case "landscape":this.Ia=5;break;case "standard":this.Ia=0;break;case "large":this.Ia=1;break;case "medium":this.Ia=2;break;case "full":this.Ia=
3;break;case "leaderboard":this.Ia=4;break;default:this.Ia=5}this.v=null;this.H=this.G=!1}ha(n,e){if(this.v)return a(e,"banner ad loaded");q.call(this,e);n={adUnitId:d.ec(this.$a,"banner"),size:this.Ia,position:this.$h,offset:0,npa:"NON_PERSONALIZED"===n?"1":"0"};this.v=new self.admob.BannerAd(n);this.v.load()}async Ma(n){this.v?this.G?b(n,"banner ad still loading"):this.H?a(n,"banner ad already shown"):(await this.v.show(),this.H=!0,a(n,"banner shown")):b(n,"banner ad not created")}async Hf(n){this.v?
this.G?b(n,"banner ad still loading"):this.H?(await this.v.hide(),this.H=!1,a(n,"banner ad hidden")):a(n,"banner ad not being shown"):b(n,"banner ad not created")}}function q(n){const e=()=>{this.G=!1;a(n,"banner ad loaded");document.removeEventListener(c.U,e);document.removeEventListener(c.V,h)},h=()=>{this.v=null;this.G=!1;b(n,"banner ad failed to load");document.removeEventListener(c.U,e);document.removeEventListener(c.V,h)};document.addEventListener(c.U,e);document.addEventListener(c.V,h)}self.qf=
l}"use strict";
{const d=self.Ua,a=d.D,b=d.u,c={get U(){return self.admob.Events.interstitialLoad},get V(){return self.admob.Events.interstitialLoadFail},get ia(){return self.admob.Events.interstitialShow},get ja(){return self.admob.Events.interstitialShowFail},get xa(){return self.admob.Events.interstitialDismiss}};class l{constructor(e,h){if(!e)return b(h,"Unit ID not specified");this.$a=e;this.v=null;this.K=this.H=this.G=!1;this.aa=null;this.g=this.J();document.addEventListener(c.xa,async()=>{this.H=!1;this.G=
!0;this.K=!1;this.g=null;this.g=this.J();q.call(this);await this.v.load()})}J(){return this.g?this.g:this.g=new Promise(e=>{this.aa=e})}La(e){this.K=e;this.aa&&this.aa(e);this.aa=this.g=null;this.g=this.J()}ha(e,h){e={adUnitId:d.ec(this.$a,"interstitial"),npa:"NON_PERSONALIZED"===e?"1":"0"};this.G=!0;this.K=this.H=!1;this.g=null;this.g=this.J();this.v=new self.admob.InterstitialAd(e);q.call(this,h);this.v.load()}async Ma(e){this.v?this.H?a(e,"interstitial ad already shown"):(this.G&&await this.J(),
await (async()=>{this.K?(n.call(this,e),await this.v.show()):(q.call(this),this.K=!1,this.g=null,this.v.load(),await this.J(),this.K?(n.call(this,e),await this.v.show()):b(e,"interstitial ad failed to load"))})()):b(e,"interstitial ad not created")}}function q(e){const h=()=>{this.G=!1;this.La(!0);e&&a(e,"interstitial ad load");document.removeEventListener(c.U,h);document.removeEventListener(c.V,g)},g=()=>{this.G=!1;this.La(!1);e&&b(e,"interstitial ad failed to load");document.removeEventListener(c.U,
h);document.removeEventListener(c.V,g)};document.addEventListener(c.U,h);document.addEventListener(c.V,g)}function n(e){const h=()=>{this.H=!0;e&&a(e,"interstitial ad show");document.removeEventListener(c.ia,h);document.removeEventListener(c.ja,g)},g=()=>{this.H=!1;e&&b(e,"interstitial ad failed to show");document.removeEventListener(c.ia,h);document.removeEventListener(c.ja,g)};document.addEventListener(c.ia,h);document.addEventListener(c.ja,g)}self.uf=l}"use strict";
{const d=self.Ua,a=d.D,b=d.u,c={get U(){return self.admob.Events.rewardedLoad},get V(){return self.admob.Events.rewardedLoadFail},get ia(){return self.admob.Events.rewardedShow},get ja(){return self.admob.Events.rewardedShowFail},get xa(){return self.admob.Events.rewardedDismiss},get Ya(){return self.admob.Events.rewardedReward}};class l{constructor(e,h){if(!e)return b(h,"Unit ID not specified");this.$a=e;this.v=null;this.K=this.H=this.G=!1;this.aa=null;this.g=this.J();this.ma=null}J(){return this.g?
this.g:this.g=new Promise(e=>{this.aa=e})}La(e){this.K=e;this.aa&&this.aa(e);this.aa=this.g=null;this.g=this.J()}ha(e,h){e={adUnitId:d.ec(this.$a,"rewarded"),npa:"NON_PERSONALIZED"===e?"1":"0"};this.G=!0;this.K=this.H=!1;this.g=null;this.g=this.J();this.v=new self.admob.RewardedAd(e);q.call(this,h);this.v.load()}async Ma(e){this.v?this.H?a(e,"rewarded ad already shown"):(this.G&&await this.J(),await (async()=>{this.K?(n.call(this,e),await this.v.show()):(q.call(this),this.K=!1,this.g=null,this.v.load(),
await this.J(),this.K?(n.call(this,e),await this.v.show()):b(e,"rewarded ad failed to load"))})()):b(e,"rewarded ad not created")}}function q(e){const h=()=>{this.G=!1;this.La(!0);e&&a(e,"rewarded ad load");document.removeEventListener(c.U,h);document.removeEventListener(c.V,g)},g=()=>{this.G=!1;this.La(!1);e&&b(e,"rewarded ad failed to load");document.removeEventListener(c.U,h);document.removeEventListener(c.V,g)};document.addEventListener(c.U,h);document.addEventListener(c.V,g)}function n(e){const h=
()=>{this.H=!0},g=w=>{this.ma=w.reward},p=()=>{this.H=!1;e&&b(e,"rewarded ad failed to show");document.removeEventListener(c.ia,h);document.removeEventListener(c.ja,p);document.removeEventListener(c.Ya,g);document.removeEventListener(c.xa,z)},z=()=>{if(null!==this.ma){const w=String(this.ma.type),v=String(this.ma.amount);e&&a(e,JSON.stringify([w,v]))}else e&&b(e,"closed with no reward");this.ma=null;this.H=!1;this.G=!0;this.K=!1;this.g=null;this.g=this.J();q.call(this);this.v.load();document.removeEventListener(c.ia,
h);document.removeEventListener(c.ja,p);document.removeEventListener(c.Ya,g);document.removeEventListener(c.xa,z)};document.addEventListener(c.ia,h);document.addEventListener(c.ja,p);document.addEventListener(c.Ya,g);document.addEventListener(c.xa,z)}self.vf=l}"use strict";
{const d=self.Ua,a=d.D,b=d.u,c={get U(){return self.admob.Events.rewardedInterstitialLoad},get V(){return self.admob.Events.rewardedInterstitialLoadFail},get ia(){return self.admob.Events.rewardedInterstitialShow},get ja(){return self.admob.Events.rewardedInterstitialShowFail},get xa(){return self.admob.Events.rewardedInterstitialDismiss},get Ya(){return self.admob.Events.rewardedInterstitialReward}};class l{constructor(e,h){if(!e)return b(h,"Unit ID not specified");this.$a=e;this.v=null;this.K=this.H=
this.G=!1;this.aa=null;this.g=this.J();this.ma=null}J(){return this.g?this.g:this.g=new Promise(e=>{this.aa=e})}La(e){this.K=e;this.aa&&this.aa(e);this.aa=this.g=null;this.g=this.J()}ha(e,h){e={adUnitId:d.ec(this.$a,"rewardedInterstitial"),npa:"NON_PERSONALIZED"===e?"1":"0"};this.G=!0;this.K=this.H=!1;this.g=null;this.g=this.J();this.v=new self.admob.RewardedInterstitialAd(e);q.call(this,h);this.v.load()}async Ma(e){this.v?this.H?a(e,"rewarded interstitial ad already shown"):(this.G&&await this.J(),
await (async()=>{this.K?(n.call(this,e),await this.v.show()):(q.call(this),this.K=!1,this.g=null,this.v.load(),await this.J(),this.K?(n.call(this,e),await this.v.show()):b(e,"rewarded interstitial ad failed to load"))})()):b(e,"rewarded interstitial ad not created")}}function q(e){const h=()=>{this.G=!1;this.La(!0);e&&a(e,"rewarded interstitial ad load");document.removeEventListener(c.U,h);document.removeEventListener(c.V,g)},g=()=>{this.G=!1;this.La(!1);e&&b(e,"rewarded interstitial ad failed to load");
document.removeEventListener(c.U,h);document.removeEventListener(c.V,g)};document.addEventListener(c.U,h);document.addEventListener(c.V,g)}function n(e){const h=()=>{this.H=!0},g=w=>{this.ma=w.reward},p=()=>{this.H=!1;e&&b(e,"rewarded interstitial ad failed to show");document.removeEventListener(c.ia,h);document.removeEventListener(c.ja,p);document.removeEventListener(c.Ya,g);document.removeEventListener(c.xa,z)},z=()=>{if(null!==this.ma){const w=String(this.ma.type),v=String(this.ma.amount);e&&a(e,
JSON.stringify([w,v]))}else e&&b(e,"closed with no reward");this.ma=null;this.H=!1;this.G=!0;this.K=!1;this.g=null;this.g=this.J();q.call(this);this.v.load();document.removeEventListener(c.ia,h);document.removeEventListener(c.ja,p);document.removeEventListener(c.Ya,g);document.removeEventListener(c.xa,z)};document.addEventListener(c.ia,h);document.addEventListener(c.ja,p);document.addEventListener(c.Ya,g);document.addEventListener(c.xa,z)}self.wf=l}"use strict";
{const d=self.Ua,a=d.D,b=d.u,c=self.cordova?"ios"===self.cordova.platformId:!1,l=self.cordova?"android"===self.cordova.platformId:!1;class q{constructor(){this.Aa="UNKNOWN";this.Ba="";this.Ib=0;this.mb="UNKNOWN";this.ua="not-determined";this.Id=!1}async bd(){d.Va.debug&&await self.consent.reset()}async je(){c&&await self.admob.requestTrackingAuthorization()}async ic(){if(l)return this.ua="not-determined";const v=self.cordova.plugins.idfa,x=await v.gi();if(!x.ti)return this.ua="authorized";switch(x.Pi){case v.Ei:return this.ua=
"not-determined";case v.Fi:return this.ua="denied";case v.Di:return this.ua="denied";case v.Ci:return this.ua="authorized"}}async Tf(v){l?a(v,"not-determined"):c&&(await p.call(this),"true"===this.Ba?await this.je():(await this.ic(),"not-determined"===this.ua&&(await n.call(this),this.Id?await this.$f():await this.je())),await this.ic(),a(v,this.ua))}async Uf(v,x,D){return await w.call(this,v,x,F=>{F?"object"===typeof F?b(D,F.message):b(D,F):b(D,"requestInfoUpdate error")})}async Vf(v,x){await w.call(this,
v,x)}async fd(v,x=!1){await e.call(this);switch(v){case "eu":x=await n.call(this);h.call(this)&&x&&await (await self.consent.loadForm()).show();break;case "always":{v=await n.call(this);const D=await p.call(this);v&&"true"===D?await (await self.consent.loadForm()).show():v&&x&&await (await self.consent.loadForm()).show()}}await e.call(this);await p.call(this);await g.call(this)}async $f(){await this.fd("always",!0)}async ne(){await e.call(this);await p.call(this);await g.call(this)}async bg(v){await this.ic();
a(v,`${this.mb}&&${this.ua}&&${this.Ba}`)}async Uc(v,x){b(v,x)}async ag(v){await this.ne();await this.ic();a(v,`${this.mb}&&${this.ua}&&${this.Ba}`)}}async function n(){return this.Id=await self.consent.getFormStatus()===self.consent.FormStatus.Available}async function e(){this.Ib=await self.consent.getConsentStatus();switch(this.Ib){case 1:return this.mb="REQUIRED";case 2:return this.mb="NOT_REQUIRED";case 3:return this.mb="OBTAINED";case 0:return this.mb="UNKNOWN"}}function h(){switch(this.Ib){case 1:return!0;
case 2:return!1;case 3:return!1;case 0:return!0}}function g(){switch(this.Ib){case 1:return this.Aa="NON_PERSONALIZED";case 2:return this.Aa="PERSONALIZED";case 3:return this.Aa="PERSONALIZED";case 0:return this.Aa="NON_PERSONALIZED"}}async function p(){if(l)switch(this.Ib){case 1:return this.Ba="true";case 2:return this.Ba="false";case 3:return this.Ba="true";case 0:return this.Ba="true"}if(c)return await z.call(this,"IABTCF_gdprApplies","getInt")?this.Ba="true":this.Ba="false"}async function z(v,
x){return new Promise(D=>{self.NativeStorage[x](v,F=>D(F),()=>D(1))})}async function w(v,x,D){let F="",H=null;if(v){switch(x){case "EEA":F=self.consent.DebugGeography.EEA;break;case "NOT_EEA":F=self.consent.DebugGeography.NotEEA;break;default:F=self.consent.DebugGeography.Disabled}H=[await d.cg]}try{return v?await self.consent.requestInfoUpdate({Ii:F,Oi:H}):await self.consent.requestInfoUpdate(),!0}catch(k){return D&&D(k),!1}}self.rf=new q}"use strict";
{const d=(q,n)=>{let e=q[0],h=q[1],g=q[2],p=q[3];e=a(h&g|~h&p,e,h,n[0],7,-680876936);p=a(e&h|~e&g,p,e,n[1],12,-389564586);g=a(p&e|~p&h,g,p,n[2],17,606105819);h=a(g&p|~g&e,h,g,n[3],22,-1044525330);e=a(h&g|~h&p,e,h,n[4],7,-176418897);p=a(e&h|~e&g,p,e,n[5],12,1200080426);g=a(p&e|~p&h,g,p,n[6],17,-1473231341);h=a(g&p|~g&e,h,g,n[7],22,-45705983);e=a(h&g|~h&p,e,h,n[8],7,1770035416);p=a(e&h|~e&g,p,e,n[9],12,-1958414417);g=a(p&e|~p&h,g,p,n[10],17,-42063);h=a(g&p|~g&e,h,g,n[11],22,-1990404162);e=a(h&g|~h&
p,e,h,n[12],7,1804603682);p=a(e&h|~e&g,p,e,n[13],12,-40341101);g=a(p&e|~p&h,g,p,n[14],17,-1502002290);h=a(g&p|~g&e,h,g,n[15],22,1236535329);e=a(h&p|g&~p,e,h,n[1],5,-165796510);p=a(e&g|h&~g,p,e,n[6],9,-1069501632);g=a(p&h|e&~h,g,p,n[11],14,643717713);h=a(g&e|p&~e,h,g,n[0],20,-373897302);e=a(h&p|g&~p,e,h,n[5],5,-701558691);p=a(e&g|h&~g,p,e,n[10],9,38016083);g=a(p&h|e&~h,g,p,n[15],14,-660478335);h=a(g&e|p&~e,h,g,n[4],20,-405537848);e=a(h&p|g&~p,e,h,n[9],5,568446438);p=a(e&g|h&~g,p,e,n[14],9,-1019803690);
g=a(p&h|e&~h,g,p,n[3],14,-187363961);h=a(g&e|p&~e,h,g,n[8],20,1163531501);e=a(h&p|g&~p,e,h,n[13],5,-1444681467);p=a(e&g|h&~g,p,e,n[2],9,-51403784);g=a(p&h|e&~h,g,p,n[7],14,1735328473);h=a(g&e|p&~e,h,g,n[12],20,-1926607734);e=a(h^g^p,e,h,n[5],4,-378558);p=a(e^h^g,p,e,n[8],11,-2022574463);g=a(p^e^h,g,p,n[11],16,1839030562);h=a(g^p^e,h,g,n[14],23,-35309556);e=a(h^g^p,e,h,n[1],4,-1530992060);p=a(e^h^g,p,e,n[4],11,1272893353);g=a(p^e^h,g,p,n[7],16,-155497632);h=a(g^p^e,h,g,n[10],23,-1094730640);e=a(h^
g^p,e,h,n[13],4,681279174);p=a(e^h^g,p,e,n[0],11,-358537222);g=a(p^e^h,g,p,n[3],16,-722521979);h=a(g^p^e,h,g,n[6],23,76029189);e=a(h^g^p,e,h,n[9],4,-640364487);p=a(e^h^g,p,e,n[12],11,-421815835);g=a(p^e^h,g,p,n[15],16,530742520);h=a(g^p^e,h,g,n[2],23,-995338651);e=a(g^(h|~p),e,h,n[0],6,-198630844);p=a(h^(e|~g),p,e,n[7],10,1126891415);g=a(e^(p|~h),g,p,n[14],15,-1416354905);h=a(p^(g|~e),h,g,n[5],21,-57434055);e=a(g^(h|~p),e,h,n[12],6,1700485571);p=a(h^(e|~g),p,e,n[3],10,-1894986606);g=a(e^(p|~h),g,
p,n[10],15,-1051523);h=a(p^(g|~e),h,g,n[1],21,-2054922799);e=a(g^(h|~p),e,h,n[8],6,1873313359);p=a(h^(e|~g),p,e,n[15],10,-30611744);g=a(e^(p|~h),g,p,n[6],15,-1560198380);h=a(p^(g|~e),h,g,n[13],21,1309151649);e=a(g^(h|~p),e,h,n[4],6,-145523070);p=a(h^(e|~g),p,e,n[11],10,-1120210379);g=a(e^(p|~h),g,p,n[2],15,718787259);h=a(p^(g|~e),h,g,n[9],21,-343485551);q[0]=e+q[0]&4294967295;q[1]=h+q[1]&4294967295;q[2]=g+q[2]&4294967295;q[3]=p+q[3]&4294967295},a=(q,n,e,h,g,p)=>{n=(n+q&4294967295)+(h+p&4294967295)&
4294967295;return(n<<g|n>>>32-g)+e&4294967295},b=q=>{const n=q.length,e=[1732584193,-271733879,-1732584194,271733878];let h;for(h=64;h<=q.length;h+=64){{var g=q.substring(h-64,h);const p=[];for(let z=0;64>z;z+=4)p[z>>2]=g.charCodeAt(z)+(g.charCodeAt(z+1)<<8)+(g.charCodeAt(z+2)<<16)+(g.charCodeAt(z+3)<<24);g=p}d(e,g)}q=q.substring(h-64);g=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];for(h=0;h<q.length;h++)g[h>>2]|=q.charCodeAt(h)<<(h%4<<3);g[h>>2]|=128<<(h%4<<3);if(55<h)for(d(e,g),h=0;16>h;h++)g[h]=0;g[14]=8*
n;d(e,g);return e},c="0123456789abcdef".split(""),l=q=>{for(let h=0;h<q.length;h++){var n=h;{var e=q[h];let g="";for(let p=0;4>p;p++)g+=c[e>>8*p+4&15]+c[e>>8*p&15];e=g}q[n]=e}return q.join("")};l(b("hello"));self.Zd=q=>l(b(q))}"use strict";
{const d=self.Ua,a=self.rf,b=self.qf,c=self.uf,l=self.vf,q=self.wf;let n=null,e=null,h=null,g=null,p=null;const z={CreateBannerAdvert:async(w,v,x,D,F)=>{await d.la(F,x)&&(x=await a.Aa,n||(n=new b(w,v,D,F)),n.ha(x,F))},ShowBannerAdvert:async w=>{if(!n)return d.u(w,"banner ad not created");n.Ma(w)},HideBannerAdvert:async w=>{if(!n)return d.u(w,"banner ad not created");n.Hf(w)},CreateInterstitialAdvert:async(w,v,x)=>{if(e)return d.D(x,"interstitial ad already created");await d.la(x,v)&&(v=await a.Aa,
e=new c(w,x),e.ha(v,x))},ShowInterstitialAdvert:async w=>{if(!e)return d.u(w,"interstitial ad not created");e.Ma(w)},CreateVideoAdvert:async(w,v,x)=>{if(h||g)return d.D(x,"video ad already created");await d.la(x,v)&&(v=await a.Aa,h=new l(w,x),h.ha(v,x))},ShowVideoAdvert:async w=>{if(!h)return d.u(w,"video ad not created");h.Ma(w)},CreateRewardedAdvert:async(w,v,x)=>{if(g||h)return d.D(x,"rewarded ad already created");await d.la(x,v)&&(v=await a.Aa,g=new l(w,x),g.ha(v,x))},ShowRewardedAdvert:async w=>
{if(!g)return d.u(w,"rewarded ad not created");g.Ma(w)},CreateRewardedInterstitialAdvert:async(w,v,x)=>{if(p)return d.D(x,"rewarded interstitial ad already created");await d.la(x,v)&&(v=await a.Aa,p=new q(w,x),p.ha(v,x))},ShowRewardedInterstitialAdvert:async w=>{if(!p)return d.u(w,"rewarded interstitial ad not created");p.Ma(w)},Configure:async(w,v,x,D,F,H,k,m,u)=>{const f=!d.Gf();d.Wf(w,v,x,D,F,H,k);if(!await d.la(u,H))return a.Uc(u,"failure to initialize");f&&await a.bd();if(!await a.Uf(H,k,u))return a.Uc(u,
"failure to update consent information");f?m?await a.fd("eu"):await a.ne():await a.fd("always");await a.bg(u)},RequestConsent:async w=>{z.Configure(d.Va.id,d.Va.mi,d.Va.ki,d.Va.pi,"always",d.Va.debug,d.Va.di,!1,w)},SetMaxAdContentRating:async(w,v)=>{if(await d.la(v)){if(!w)return d.u(v,"Label not specified");try{d.hd("maxAdContentRating",w),d.D(v,"")}catch(x){d.u(v,"invalid label")}}},TagForChildDirectedTreatment:async(w,v)=>{if(await d.la(v))try{d.hd("tagForChildDirectedTreatment",1===w?!0:!1),d.D(v,
"")}catch(x){d.u(v,"invalid label")}},TagForUnderAgeOfConsent:async(w,v)=>{if(await d.la(v))try{d.hd("tagForUnderAgeOfConsent",1===w?!0:!1),d.D(v,"")}catch(x){d.u(v,"invalid label")}},RequestIDFA:async w=>{await d.la(w)&&a.Tf(w)},StatusUpdate:async(w,v,x)=>{if(!await d.la(x,w))return a.Uc(x,"failure to initialize");await a.Vf(w,v);await a.ag(x)}};self.oa||(self.oa={});self.oa.ni=z}"use strict";
{const d={},a=(g,p)=>d[g]=p,b=g=>new Promise(p=>setTimeout(p,g));let c=null,l=null,q=null,n=null,e=null;function h(g,p){const z=p.slice(0,-1);p=p[p.length-1];console.log(g,z);return[z,p]}a("CreateBannerAdvert",async(...g)=>{[,g]=h("CreateBannerAdvert",g);await b(50);c?g("Banner already exists"):(c="ready",g(null,"Created banner"))});a("ShowBannerAdvert",async(...g)=>{[,g]=h("ShowBannerAdvert",g);await b(50);"ready"!=c?g("Banner cannot be shown"):(c="shown",g(null,"Showed banner"))});a("HideBannerAdvert",
async(...g)=>{[,g]=h("HideBannerAdvert",g);await b(50);"shown"!=c?g("Banner cannot be hidden"):(c=null,g(null,"Hid banner"))});a("CreateInterstitialAdvert",async(...g)=>{[,g]=h("CreateInterstitialAdvert",g);await b(50);l?g("Intersitial already exists"):(l="ready",g(null,"Created interstitial"))});a("ShowInterstitialAdvert",async(...g)=>{[,g]=h("ShowInterstitialAdvert",g);await b(50);"ready"!=l?g("Cannot show interstitial"):(l=null,g(null,"Interstitial shown"))});a("CreateVideoAdvert",async(...g)=>
{[,g]=h("CreateVideoAdvert",g);await b(50);q?g("Video already exists"):(q="ready",g(null,"Created video"))});a("ShowVideoAdvert",async(...g)=>{[,g]=h("ShowVideoAdvert",g);await b(50);"ready"!=q?g("Cannot show video"):(q=null,g(null,'["example type", 20]'))});a("CreateRewardedAdvert",async(...g)=>{[,g]=h("CreateRewardedAdvert",g);await b(50);n?g("Rewarded already exists"):(n="ready",g(null,"Created rewarded"))});a("ShowRewardedAdvert",async(...g)=>{[,g]=h("ShowRewardedAdvert",g);await b(50);"ready"!=
n?g("Cannot show rewarded"):(n=null,g(null,'["example type", 20]'))});a("CreateRewardedInterstitialAdvert",async(...g)=>{[,g]=h("CreateRewardedInterstitialAdvert",g);await b(50);e?g("Rewarded intersitial already exists"):(e="ready",g(null,"Created rewarded interstitial"))});a("ShowRewardedInterstitialAdvert",async(...g)=>{[,g]=h("ShowRewardedInterstitialAdvert",g);await b(50);"ready"!=e?g("Cannot show rewarded interstitial"):(e=null,g(null,"Rewarded interstitial shown"))});a("Configure",async(...g)=>
{[,g]=h("Configure",g);await b(50);g(null,"PERSONALIZED&&true")});a("RequestConsent",async(...g)=>{[,g]=h("RequestConsent",g);await b(50);g(null,"PERSONALIZED&&true")});a("RequestIDFA",async(...g)=>{[,g]=h("RequestIDFA",g);await b(50);g(null,"authorized")});self.oa||(self.oa={});self.oa.Ji=d}"use strict";
{const d=self.Ua,a={};let b=!1,c=null;const l=async e=>{if(!a.webAdsScriptLoaded)return d.u(e,"advert script not loaded, likely blocked by an ad blocker"),!1;b||(self.adsbygoogle=self.adsbygoogle||[],self.adBreak=self.adConfig=h=>self.adsbygoogle.push(h),b=!0);return c?c:c=new Promise(h=>{self.adConfig({preloadAdBreaks:"on",onReady:()=>h(!0)})})},q=()=>{a.domSideHandler.B.Cb("runtime","visibilitychange",{hidden:!0})},n=()=>{a.domSideHandler.B.Cb("runtime","visibilitychange",{hidden:!1})};a.CreateBannerAdvert=
async(e,h,g,p,z)=>{d.u(z,"banner ads not supported in web platform")};a.ShowBannerAdvert=async e=>{d.u(e,"banner ads not supported in web platform")};a.HideBannerAdvert=async e=>{d.u(e,"banner ads not supported in web platform")};a.CreateInterstitialAdvert=async(e,h,g)=>{await l(g)&&d.D(g,"interstitial ad created")};a.ShowInterstitialAdvert=async e=>{await l(e)&&self.adBreak({type:"next",beforeAd:()=>q(),afterAd:()=>n(),adBreakDone:h=>{switch(h.breakStatus){case "viewed":case "dismissed":d.D(e,"interstitial ad show");
break;default:console.table(h),d.u(e,"interstitial ad failed to show")}}})};a.CreateVideoAdvert=async(e,h,g)=>{d.u(g,"video ads are deprecated")};a.ShowVideoAdvert=async e=>{d.u(e,"video ads are deprecated")};a.CreateRewardedAdvert=async(e,h,g)=>{await l(g)&&d.D(g,"rewarded ad created")};a.ShowRewardedAdvert=async e=>{await l(e)&&self.adBreak({type:"reward",beforeAd:()=>q(),afterAd:()=>n(),adBreakDone:h=>{switch(h.breakStatus){case "viewed":case "dismissed":d.D(e,"rewarded ad show");break;case "ignored":d.u(e,
"rewarded ad ignored");break;default:console.table(h),d.u(e,"rewarded ad failed to show")}},beforeReward:h=>{h()},adDismissed:()=>{d.u(e,"closed with no reward")},adViewed:()=>{d.D(e,JSON.stringify(["Reward",1]))}})};a.CreateRewardedInterstitialAdvert=async(e,h,g)=>{await l(g)&&d.D(g,"rewarded interstitial ad created")};a.ShowRewardedInterstitialAdvert=async e=>{await l(e)&&self.adBreak({type:"reward",beforeAd:()=>q(),afterAd:()=>n(),adBreakDone:h=>{switch(h.breakStatus){case "viewed":case "dismissed":d.D(e,
"rewarded interstitial ad show");break;case "ignored":d.u(e,"rewarded interstitial ad ignored");break;default:console.table(h),d.u(e,"rewarded interstitial ad failed to show")}},beforeReward:h=>{h()},adDismissed:()=>{d.u(e,"closed with no reward")},adViewed:()=>{d.D(e,JSON.stringify(["Reward",1]))}})};a.Configure=async(e,h,g,p,z,w,v,x,D)=>{a.webAdsScriptLoaded?d.D(D,"UNKNOWN&&not-determined&&true"):d.u(D,"advert script not loaded, likely blocked by an ad blocker")};a.RequestConsent=async e=>{d.D(e,
"UNKNOWN&&not-determined&&true")};a.SetMaxAdContentRating=async(e,h)=>{d.u(h,"setting max ad content rating not supported in web platform")};a.TagForChildDirectedTreatment=async(e,h)=>{d.u(h,"tagging for children not supported in web platform")};a.TagForUnderAgeOfConsent=async(e,h)=>{d.u(h,"tagging for under age of consent not supported in web platform")};a.RequestIDFA=async e=>{d.D(e,"not-determined")};a.StatusUpdate=async(e,h,g)=>{d.D(g,"UNKNOWN&&not-determined&&true")};self.oa||(self.oa={});self.oa.wi=
a}"use strict";
{let d=!1;self.pa.Ta(class extends self.Ka{constructor(a){super(a,"advert");a=b=>[b,c=>this.lg(b,c)];L(this,[a("CreateBannerAdvert"),a("ShowBannerAdvert"),a("HideBannerAdvert"),a("CreateInterstitialAdvert"),a("ShowInterstitialAdvert"),a("CreateVideoAdvert"),a("ShowVideoAdvert"),a("CreateRewardedAdvert"),a("ShowRewardedAdvert"),a("CreateRewardedInterstitialAdvert"),a("ShowRewardedInterstitialAdvert"),a("Configure"),a("RequestConsent"),a("SetUserPersonalisation"),a("SetMaxAdContentRating"),a("TagForChildDirectedTreatment"),
a("TagForUnderAgeOfConsent"),a("RequestIDFA"),a("StatusUpdate"),(b=>[b,c=>this.hg(c[0],c[1])])("AddScript")])}re(){if(self.cordova)return self.oa.ni;if(!self.cordova)return self.oa.wi}async lg(a,b){const c=this.re();c.domSideHandler||(c.domSideHandler=this);if(!c)throw d||(d=!0,console.warn("The Mobile Advert plugin is not loaded. Please note that it only works in Android or iOS exports")),Error("advert plugin not loaded");return new Promise((l,q)=>{(0,c[a])(...b,(n,e)=>{n?q(n):l(e)})})}async hg(a,
b=null){const c=this.re();c.webAdsScriptLoaded=!1;return new Promise(l=>{const q=document.createElement("script");if(b)for(let n in b)q.setAttribute(n,b[n]);q.onload=function(){c.webAdsScriptLoaded=!0;l()};q.onerror=function(){c.webAdsScriptLoaded=!1;l()};q.src=a;document.head.appendChild(q)})}})}"use strict";
{const d=180/Math.PI;self.wa=class extends self.Ka{constructor(a){super(a,"audio");this.yc=this.c=null;this.Ac=this.Kd=!1;this.Sa=()=>this.Mh();this.ra=[];this.M=[];this.Da=null;this.Pe="";this.Qe=-1;this.Xb=new Map;this.Od=1;this.Pa=!1;this.Ud=0;this.Pc=1;this.Hd=0;this.Te="HRTF";this.Je="inverse";this.Ue=600;this.Se=1E4;this.We=1;this.Le=this.Sd=!1;this.Ze=this.B.Kf();this.sa=new Map;this.lb=new Set;this.Md=!1;this.Pd="";this.cb=null;self.C3Audio_OnMicrophoneStream=(b,c)=>this.Vg(b,c);this.xc=null;
self.C3Audio_GetOutputStream=()=>this.Og();self.C3Audio_DOMInterface=this;L(this,[["create-audio-context",b=>this.rg(b)],["play",b=>this.mh(b)],["stop",b=>this.Jh(b)],["stop-all",()=>this.Kh()],["set-paused",b=>this.Ch(b)],["set-volume",b=>this.Hh(b)],["fade-volume",b=>this.wg(b)],["set-master-volume",b=>this.Ah(b)],["set-muted",b=>this.Bh(b)],["set-silent",b=>this.Eh(b)],["set-looping",b=>this.zh(b)],["set-playback-rate",b=>this.Dh(b)],["seek",b=>this.th(b)],["preload",b=>this.nh(b)],["unload",b=>
this.Nh(b)],["unload-all",()=>this.Oh()],["set-suspended",b=>this.Fh(b)],["get-suspended",()=>this.Ag()],["add-effect",b=>this.oe(b)],["set-effect-param",b=>this.wh(b)],["remove-effects",b=>this.ph(b)],["tick",b=>this.hh(b)],["load-state",b=>this.Tg(b)]])}async rg(a){a.isiOSCordova&&(this.Sd=!0);this.Ud=a.timeScaleMode;this.Te=["equalpower","HRTF","soundfield"][a.panningModel];this.Je=["linear","inverse","exponential"][a.distanceModel];this.Ue=a.refDistance;this.Se=a.maxDistance;this.We=a.rolloffFactor;
var b={latencyHint:a.latencyHint};this.Ze||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.c=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.c=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.pe();this.c.onstatechange=()=>{"running"!==this.c.state&&this.pe()};this.yc=this.c.createGain();this.yc.connect(this.c.destination);b=a.listenerPos;this.c.listener.setPosition(b[0],b[1],b[2]);this.c.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=
()=>this.Vc();try{await Promise.all(a.preloadList.map(c=>this.oc(c.originalUrl,c.url,c.type,!1)))}catch(c){console.error("[Construct 3] Preloading sounds failed: ",c)}return{sampleRate:this.c.sampleRate}}pe(){this.Ac||(this.Kd=!1,window.addEventListener("pointerup",this.Sa,!0),window.addEventListener("touchend",this.Sa,!0),window.addEventListener("click",this.Sa,!0),window.addEventListener("keydown",this.Sa,!0),this.Ac=!0)}tg(){this.Ac&&(this.Kd=!0,window.removeEventListener("pointerup",this.Sa,!0),
window.removeEventListener("touchend",this.Sa,!0),window.removeEventListener("click",this.Sa,!0),window.removeEventListener("keydown",this.Sa,!0),this.Ac=!1)}Mh(){if(!this.Kd){var a=this.c;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),c=a.createBufferSource();c.buffer=b;c.connect(a.destination);c.start(0);"running"===a.state&&this.tg()}}ga(){return this.c}Vc(){return this.c.currentTime}Wa(){return this.yc}de(a){return(a=this.sa.get(a.toLowerCase()))?a[0].$():this.Wa()}cf(a,
b){a=a.toLowerCase();let c=this.sa.get(a);c||(c=[],this.sa.set(a,c));b.yh(c.length);b.Gh(a);c.push(b);this.Ce(a)}Ce(a){let b=this.Wa();const c=this.sa.get(a);if(c&&c.length){b=c[0].$();for(let l=0,q=c.length;l<q;++l){const n=c[l];l+1===q?n.ca(this.Wa()):n.ca(c[l+1].$())}}for(const l of this.Ja(a))l.Rf(b);this.cb&&this.Pd===a&&(this.cb.disconnect(),this.cb.connect(b))}hc(){return this.Od}jc(){return this.Pa}xh(){this.Le=!0}Bf(a,b){return b?this.B.Ph(a).then(c=>{const l=this.c.createBuffer(1,c.length,
48E3);l.getChannelData(0).set(c);return l}):new Promise((c,l)=>{this.c.decodeAudioData(a,c,l)})}Za(a){this.B.Za(a)}hb(a){this.B.hb(a)}ie(a){let b=0;for(let c=0,l=this.M.length;c<l;++c){const q=this.M[c];this.M[b]=q;q.W===a?q.f():++b}this.M.length=b}Sf(){let a=0;for(let b=0,c=this.ra.length;b<c;++b){const l=this.ra[b];this.ra[a]=l;l.Xa()?l.f():++a}this.ra.length=a}*Ja(a){if(a)for(const b of this.M)self.wa.Cf(b.na,a)&&(yield b);else this.Da&&!this.Da.da()&&(yield this.Da)}async oc(a,b,c,l,q){for(const n of this.ra)if(n.zb()===
b)return await n.ha(),n;if(q)return null;l&&(this.Sd||this.Le)&&this.Sf();q="audio/webm; codecs=opus"===c&&!this.Ze;l&&q&&this.xh();a=!l||this.Sd||q?new self.xf(this,a,b,c,l,q):new self.sf(this,a,b,c,l);this.ra.push(a);await a.ha();return a}async ld(a,b,c,l,q){for(const n of this.M)if(n.zb()===b&&(n.Sc()||q))return n.Yf(l),n;a=await this.oc(a,b,c,q);l="html5"===a.Cd?new self.tf(a.j,a,l):new self.yf(a.j,a,l);this.M.push(l);return l}fg(a){let b=this.Xb.get(a);if(!b){let c=null;b={Wd:0,li:new Promise(l=>
c=l),resolve:c};this.Xb.set(a,b)}b.Wd++}qh(a){const b=this.Xb.get(a);if(!b)throw Error("expected pending tag");b.Wd--;0===b.Wd&&(b.resolve(),this.Xb.delete(a))}gd(a){a||(a=this.Pe);return(a=this.Xb.get(a))?a.li:Promise.resolve()}pc(){if(0<this.lb.size)M(this);else for(const a of this.M)if(a.ee()){M(this);break}}ib(){for(var a of this.lb)a.ib();a=this.Vc();for(var b of this.M)b.ib(a);b=this.M.filter(c=>c.ee()).map(c=>c.yb());B(this,"state",{tickCount:this.Qe,audioInstances:b,analysers:[...this.lb].map(c=>
c.Ef())});0===b.length&&0===this.lb.size&&this.Bc&&(this.B.rh(this.$e),this.Bc=!1)}ad(a,b,c){B(this,"trigger",{type:a,tag:b,aiid:c})}async mh(a){const b=a.originalUrl,c=a.url,l=a.type,q=a.isMusic,n=a.tag,e=a.isLooping,h=a.vol,g=a.pos,p=a.panning;let z=a.off;0<z&&!a.trueClock&&(this.c.getOutputTimestamp?(a=this.c.getOutputTimestamp(),z=z-a.performanceTime/1E3+a.contextTime):z=z-performance.now()/1E3+this.c.currentTime);this.Pe=n;this.fg(n);try{this.Da=await this.ld(b,c,l,n,q),p?(this.Da.lc(!0),this.Da.Xf(p.x,
p.y,p.angle,p.innerAngle,p.outerAngle,p.outerGain),p.hasOwnProperty("uid")&&this.Da.Zf(p.uid)):this.Da.lc(!1),this.Da.Play(e,h,g,z)}catch(w){console.error("[Construct 3] Audio: error starting playback: ",w);return}finally{this.qh(n)}M(this)}Jh(a){a=a.tag;for(const b of this.Ja(a))b.Na()}Kh(){for(const a of this.M)a.Na()}Ch(a){const b=a.tag;a=a.paused;for(const c of this.Ja(b))a?c.Bb():c.kc();this.pc()}Hh(a){const b=a.tag;a=a.vol;for(const c of this.Ja(b))c.nc(a)}async wg(a){const b=a.tag,c=a.vol,
l=a.duration;a=a.stopOnEnd;await this.gd(b);for(const q of this.Ja(b))q.Df(c,l,a);this.pc()}Ah(a){this.Od=a.vol;for(const b of this.M)b.vc()}Bh(a){const b=a.tag;a=a.isMuted;for(const c of this.Ja(b))c.ke(a)}Eh(a){this.Pa=a.isSilent;this.B.mc(this.Pa);for(const b of this.M)b.uc()}zh(a){const b=a.tag;a=a.isLooping;for(const c of this.Ja(b))c.dd(a)}async Dh(a){const b=a.tag;a=a.rate;await this.gd(b);for(const c of this.Ja(b))c.me(a)}async th(a){const b=a.tag;a=a.pos;await this.gd(b);for(const c of this.Ja(b))c.cd(a)}async nh(a){const b=
a.originalUrl,c=a.url,l=a.type;a=a.isMusic;try{await this.ld(b,c,l,"",a)}catch(q){console.error("[Construct 3] Audio: error preloading: ",q)}}async Nh(a){if(a=await this.oc("",a.url,a.type,a.isMusic,!0))a.f(),a=this.ra.indexOf(a),-1!==a&&this.ra.splice(a,1)}Oh(){for(const a of this.ra)a.f();this.ra.length=0}Fh(a){a=a.isSuspended;!a&&this.c.resume&&this.c.resume();for(const b of this.M)b.ed(a);a&&this.c.suspend&&this.c.suspend()}Ag(){return this.c?this.c.state:"suspended"}hh(a){this.Pc=a.timeScale;
this.Hd=a.gameTime;this.Qe=a.tickCount;if(0!==this.Ud)for(var b of this.M)b.kb();(b=a.listenerPos)&&this.c.listener.setPosition(b[0],b[1],b[2]);for(const c of a.instPans){a=c.uid;for(const l of this.M)l.Ca===a&&l.le(c.x,c.y,c.angle)}}async oe(a){var b=a.type;const c=a.tag;var l=a.params;if("filter"===b)l=new self.jf(this,...l);else if("delay"===b)l=new self.gf(this,...l);else if("convolution"===b){b=null;try{b=await this.oc(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(q){console.log("[Construct 3] Audio: error loading convolution: ",
q);return}l=new self.ff(this,b.qa,...l);l.uh(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)l=new self.kf(this,...l);else if("phaser"===b)l=new self.mf(this,...l);else if("gain"===b)l=new self.lf(this,...l);else if("tremolo"===b)l=new self.pf(this,...l);else if("ringmod"===b)l=new self.nf(this,...l);else if("distortion"===b)l=new self.hf(this,...l);else if("compressor"===b)l=new self.ef(this,...l);else if("analyser"===b)l=new self.df(this,...l);else throw Error("invalid effect type");this.cf(c,
l);this.Be()}wh(a){const b=a.index,c=a.param,l=a.value,q=a.ramp,n=a.time;a=this.sa.get(a.tag);!a||0>b||b>=a.length||(a[b].ka(c,l,q,n),this.Be())}ph(a){a=a.tag.toLowerCase();const b=this.sa.get(a);if(b&&b.length){for(const c of b)c.f();this.sa.delete(a);this.Ce(a)}}eg(a){this.lb.add(a);this.pc()}oh(a){this.lb.delete(a)}Be(){this.Md||(this.Md=!0,Promise.resolve().then(()=>this.ug()))}ug(){const a={};for(const [b,c]of this.sa)a[b]=c.map(l=>l.yb());B(this,"fxstate",{fxstate:a});this.Md=!1}async Tg(a){const b=
a.saveLoadMode;if(3!==b)for(var c of this.M)c.Xa()&&1===b||(c.Xa()||2!==b)&&c.Na();for(const l of this.sa.values())for(const q of l)q.f();this.sa.clear();this.Pc=a.timeScale;this.Hd=a.gameTime;c=a.listenerPos;this.c.listener.setPosition(c[0],c[1],c[2]);this.Pa=a.isSilent;this.B.mc(this.Pa);this.Od=a.masterVolume;c=[];for(const l of Object.values(a.effects))c.push(Promise.all(l.map(q=>this.oe(q))));await Promise.all(c);await Promise.all(a.playing.map(l=>this.Eg(l,b)));this.pc()}async Eg(a,b){if(3!==
b){var c=a.bufferOriginalUrl,l=a.bufferUrl,q=a.bufferType,n=a.isMusic,e=a.tag,h=a.isLooping,g=a.volume,p=a.playbackTime;if(!n||1!==b)if(n||2!==b){b=null;try{b=await this.ld(c,l,q,e,n)}catch(z){console.error("[Construct 3] Audio: error loading audio state: ",z);return}b.Pf(a.pan);b.Play(h,g,p,0);a.isPlaying||b.Bb();b.pd(a)}}}Vg(a,b){this.cb&&this.cb.disconnect();this.Pd=b.toLowerCase();this.cb=this.c.createMediaStreamSource(a);this.cb.connect(this.de(this.Pd))}Og(){this.xc||(this.xc=this.c.createMediaStreamDestination(),
this.yc.connect(this.xc));return this.xc.stream}static Cf(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static dg(a){return a*d}static Af(a){return Math.pow(10,a/20)}static ce(a){return Math.max(Math.min(self.wa.Af(a),1),0)}static Of(a){return Math.log(a)/Math.log(10)*20}static Nf(a){return self.wa.Of(Math.max(Math.min(a,1),0))}static ei(a,b){return 1-Math.exp(-b*a)}};self.pa.Ta(self.wa)}"use strict";
self.$d=class{constructor(d,a,b,c,l){this.j=d;this.Zh=a;this.fb=b;this.ba=c;this.Th=l;this.Cd="";this.g=null}f(){this.g=this.j=null}od(){}ha(){this.g||(this.g=this.od());return this.g}ga(){return this.j.ga()}Xc(){return this.Zh}zb(){return this.fb}Wc(){return this.ba}Xa(){return this.Th}ya(){}};"use strict";
self.sf=class extends self.$d{constructor(d,a,b,c,l){super(d,a,b,c,l);this.Cd="html5";this.S=new Audio;this.S.crossOrigin="anonymous";this.S.autoplay=!1;this.S.preload="auto";this.Rb=this.Sb=null;this.S.addEventListener("canplaythrough",()=>!0);this.Wb=this.ga().createGain();this.Ub=null;this.S.addEventListener("canplay",()=>{this.Sb&&(this.Sb(),this.Rb=this.Sb=null);!this.Ub&&this.S&&(this.Ub=this.ga().createMediaElementSource(this.S),this.Ub.connect(this.Wb))});this.onended=null;this.S.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.S.addEventListener("error",q=>{console.error(`[Construct 3] Audio '${this.fb}' error: `,q);this.Rb&&(this.Rb(q),this.Rb=this.Sb=null)})}f(){this.j.ie(this);this.Wb.disconnect();this.Wb=null;this.Ub.disconnect();this.Ub=null;this.S&&!this.S.paused&&this.S.pause();this.S=this.onended=null;super.f()}od(){return new Promise((d,a)=>{this.Sb=d;this.Rb=a;this.S.src=this.fb})}Z(){return this.S}ya(){return this.S.duration}};"use strict";
async function X(d){if(d.ab)return d.ab;var a=d.j.B;if("cordova"===a.A&&a.ge(d.fb)&&a.Ob)d.ab=await a.dc(d.fb);else{a=await fetch(d.fb);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);d.ab=await a.arrayBuffer()}}async function aa(d){if(d.qa)return d.qa;d.qa=await d.j.Bf(d.ab,d.Yh);d.ab=null}
self.xf=class extends self.$d{constructor(d,a,b,c,l,q){super(d,a,b,c,l);this.Cd="webaudio";this.qa=this.ab=null;this.Yh=!!q}f(){this.j.ie(this);this.qa=this.ab=null;super.f()}async od(){try{await X(this),await aa(this)}catch(d){console.error(`[Construct 3] Failed to load audio '${this.fb}': `,d)}}ya(){return this.qa?this.qa.duration:0}};"use strict";
{let d=0;self.ae=class{constructor(a,b,c){this.j=a;this.W=b;this.na=c;this.wc=d++;this.X=this.ga().createGain();this.X.connect(this.Wa());this.I=null;this.Pb=!1;this.Ga=[0,0,0];this.Fa=[0,0,0];this.P=!0;this.fa=this.Ha=this.O=!1;this.ac=1;this.nb=!1;this.Ra=1;a=this.j.Ud;this.Nd=1===a&&!this.Xa()||2===a;this.Lb=this.Ca=-1;this.Ye=!1}f(){this.W=this.j=null;this.I&&(this.I.disconnect(),this.I=null);this.X.disconnect();this.X=null}ga(){return this.j.ga()}Wa(){return this.j.de(this.na)}hc(){return this.j.hc()}fc(){return this.Nd?
this.j.Hd:performance.now()/1E3}Xc(){return this.W.Xc()}zb(){return this.W.zb()}Wc(){return this.W.Wc()}Xa(){return this.W.Xa()}Yf(a){this.na=a}da(){}Sc(){}IsPlaying(){return!this.P&&!this.O&&!this.da()}ee(){return!this.P&&!this.da()}gb(){}ya(){return this.W.ya()}Play(){}Na(){}Bb(){}kc(){}nc(a){this.ac=a;this.X.gain.cancelScheduledValues(0);this.Lb=-1;this.X.gain.value=this.Yc()}Df(a,b,c){if(!this.nb){a*=this.hc();var l=this.X.gain;l.cancelScheduledValues(0);var q=this.j.Vc();b=q+b;l.setValueAtTime(l.value,
q);l.linearRampToValueAtTime(a,b);this.ac=a;this.Lb=b;this.Ye=c}}vc(){this.nc(this.ac)}ib(a){-1!==this.Lb&&a>=this.Lb&&(this.Lb=-1,this.Ye&&this.Na(),this.j.ad("fade-ended",this.na,this.wc))}Yc(){const a=this.ac*this.hc();return isFinite(a)?a:0}ke(a){a=!!a;this.nb!==a&&(this.nb=a,this.uc())}jc(){return this.j.jc()}uc(){}dd(){}me(a){this.Ra!==a&&(this.Ra=a,this.kb())}kb(){}cd(){}ed(){}lc(a){a=!!a;this.Pb!==a&&((this.Pb=a)?(this.I||(this.I=this.ga().createPanner(),this.I.panningModel=this.j.Te,this.I.distanceModel=
this.j.Je,this.I.refDistance=this.j.Ue,this.I.maxDistance=this.j.Se,this.I.rolloffFactor=this.j.We),this.X.disconnect(),this.X.connect(this.I),this.I.connect(this.Wa())):(this.I.disconnect(),this.X.disconnect(),this.X.connect(this.Wa())))}Xf(a,b,c,l,q,n){this.Pb&&(this.le(a,b,c),a=self.wa.dg,this.I.coneInnerAngle=a(l),this.I.coneOuterAngle=a(q),this.I.coneOuterGain=n)}le(a,b,c){this.Pb&&(this.Ga[0]=a,this.Ga[1]=b,this.Ga[2]=0,this.Fa[0]=Math.cos(c),this.Fa[1]=Math.sin(c),this.Fa[2]=0,this.I.setPosition(...this.Ga),
this.I.setOrientation(...this.Fa))}Zf(a){this.Ca=a}Zc(){}Rf(a){const b=this.I||this.X;b.disconnect();b.connect(a)}yb(){return{aiid:this.wc,tag:this.na,duration:this.ya(),volume:this.ac,isPlaying:this.IsPlaying(),playbackTime:this.gb(),playbackRate:this.Ra,uid:this.Ca,bufferOriginalUrl:this.Xc(),bufferUrl:"",bufferType:this.Wc(),isMusic:this.Xa(),isLooping:this.fa,isMuted:this.nb,resumePosition:this.Zc(),pan:this.Ff()}}pd(a){this.me(a.playbackRate);this.ke(a.isMuted)}Ff(){if(!this.I)return null;const a=
this.I;return{pos:this.Ga,orient:this.Fa,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.Ca}}Pf(a){if(a){this.lc(!0);a=this.I;var b=a.pos;this.Ga[0]=b[0];this.Ga[1]=b[1];this.Ga[2]=b[2];b=a.orient;this.Fa[0]=b[0];this.Fa[1]=b[1];this.Fa[2]=b[2];a.setPosition(...this.Ga);a.setOrientation(...this.Fa);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.Ca=a.uid}else this.lc(!1)}}}"use strict";
self.tf=class extends self.ae{constructor(d,a,b){super(d,a,b);this.W.Wb.connect(this.X);this.W.onended=()=>this.sd()}f(){this.Na();this.W.Wb.disconnect();super.f()}Z(){return this.W.Z()}sd(){this.P=!0;this.Ca=-1;this.j.ad("ended",this.na,this.wc)}da(){return this.Z().ended}Sc(){return this.P?!0:this.da()}gb(){let d=this.Z().currentTime;this.fa||(d=Math.min(d,this.ya()));return d}Play(d,a,b){const c=this.Z();1!==c.playbackRate&&(c.playbackRate=1);c.loop!==d&&(c.loop=d);this.nc(a);c.muted&&(c.muted=
!1);if(c.currentTime!==b)try{c.currentTime=b}catch(l){console.warn(`[Construct 3] Exception seeking audio '${this.W.zb()}' to position '${b}': `,l)}this.j.Za(c);this.O=this.P=!1;this.fa=d;this.Ra=1}Na(){const d=this.Z();d.paused||d.pause();this.j.hb(d);this.P=!0;this.O=!1;this.Ca=-1}Bb(){if(!(this.O||this.P||this.da())){var d=this.Z();d.paused||d.pause();this.j.hb(d);this.O=!0}}kc(){!this.O||this.P||this.da()||(this.j.Za(this.Z()),this.O=!1)}uc(){this.Z().muted=this.nb||this.jc()}dd(d){d=!!d;this.fa!==
d&&(this.fa=d,this.Z().loop=d)}kb(){let d=this.Ra;this.Nd&&(d*=this.j.Pc);try{this.Z().playbackRate=d}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${d}':`,a)}}cd(d){if(!this.P&&!this.da())try{this.Z().currentTime=d}catch(a){console.warn(`[Construct 3] Error seeking audio to '${d}': `,a)}}Zc(){return this.gb()}ed(d){d?this.IsPlaying()?(this.Z().pause(),this.Ha=!0):this.Ha=!1:this.Ha&&(this.j.Za(this.Z()),this.Ha=!1)}};"use strict";
function Y(d){d.l&&d.l.disconnect();d.l=null;d.Gb=null}
self.yf=class extends self.ae{constructor(d,a,b){super(d,a,b);this.l=null;this.Gc=c=>this.sd(c);this.Jd=!0;this.Gb=null;this.Y=this.Hc=this.Ic=0;this.Qd=1}f(){this.Na();Y(this);this.Gc=null;super.f()}sd(d){this.O||this.Ha||d.target!==this.Gb||(this.P=this.Jd=!0,this.Ca=-1,Y(this),this.j.ad("ended",this.na,this.wc))}da(){return!this.P&&this.l&&this.l.loop||this.O?!1:this.Jd}Sc(){return!this.l||this.P?!0:this.da()}gb(){let d;d=this.O?this.Y:this.Hc+(this.fc()-this.Ic)*this.Ra;this.fa||(d=Math.min(d,
this.ya()));return d}Play(d,a,b,c){this.Qd=1;this.nc(a);Y(this);this.l=this.ga().createBufferSource();this.l.buffer=this.W.qa;this.l.connect(this.X);this.Gb=this.l;this.l.onended=this.Gc;this.l.loop=d;this.l.start(c,b);this.O=this.P=this.Jd=!1;this.fa=d;this.Ra=1;this.Ic=this.fc();this.Hc=b}Na(){if(this.l)try{this.l.stop(0)}catch(d){}this.P=!0;this.O=!1;this.Ca=-1}Bb(){this.O||this.P||this.da()||(this.Y=this.gb(),this.fa&&(this.Y%=this.ya()),this.O=!0,this.l.stop(0))}kc(){!this.O||this.P||this.da()||
(Y(this),this.l=this.ga().createBufferSource(),this.l.buffer=this.W.qa,this.l.connect(this.X),this.Gb=this.l,this.l.onended=this.Gc,this.l.loop=this.fa,this.vc(),this.kb(),this.l.start(0,this.Y),this.Ic=this.fc(),this.Hc=this.Y,this.O=!1)}Yc(){return super.Yc()*this.Qd}uc(){this.Qd=this.nb||this.jc()?0:1;this.vc()}dd(d){d=!!d;this.fa!==d&&(this.fa=d,this.l&&(this.l.loop=d))}kb(){let d=this.Ra;this.Nd&&(d*=this.j.Pc);this.l&&(this.l.playbackRate.value=d)}cd(d){this.P||this.da()||(this.O?this.Y=d:(this.Bb(),
this.Y=d,this.kc()))}Zc(){return this.Y}ed(d){d?this.IsPlaying()?(this.Ha=!0,this.Y=this.gb(),this.fa&&(this.Y%=this.ya()),this.l.stop(0)):this.Ha=!1:this.Ha&&(Y(this),this.l=this.ga().createBufferSource(),this.l.buffer=this.W.qa,this.l.connect(this.X),this.Gb=this.l,this.l.onended=this.Gc,this.l.loop=this.fa,this.vc(),this.kb(),this.l.start(0,this.Y),this.Ic=this.fc(),this.Hc=this.Y,this.Ha=!1)}pd(d){super.pd(d);this.Y=d.resumePosition}};"use strict";
{class d{constructor(a){this.j=a;this.c=a.ga();this.Me=-1;this.ba=this.na="";this.h=null}f(){this.c=null}yh(a){this.Me=a}Gh(a){this.na=a}s(){return this.c.createGain()}$(){}ca(){}o(a,b,c,l){a.cancelScheduledValues(0);if(0===l)a.value=b;else{var q=this.c.currentTime;l+=q;switch(c){case 0:a.setValueAtTime(b,l);break;case 1:a.setValueAtTime(a.value,q);a.linearRampToValueAtTime(b,l);break;case 2:a.setValueAtTime(a.value,q),a.exponentialRampToValueAtTime(b,l)}}}yb(){return{type:this.ba,tag:this.na,params:this.h}}}
self.jf=class extends d{constructor(a,b,c,l,q,n,e){super(a);this.ba="filter";this.h=[b,c,l,q,n,e];this.m=this.s();this.b=this.s();this.b.gain.value=e;this.a=this.s();this.a.gain.value=1-e;this.F=this.c.createBiquadFilter();this.F.type=b;this.F.frequency.value=c;this.F.detune.value=l;this.F.Q.value=q;this.F.gain.vlaue=n;this.m.connect(this.F);this.m.connect(this.a);this.F.connect(this.b)}f(){this.m.disconnect();this.F.disconnect();this.b.disconnect();this.a.disconnect();super.f()}ca(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}$(){return this.m}ka(a,b,c,l){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.h[5]=b;this.o(this.b.gain,b,c,l);this.o(this.a.gain,1-b,c,l);break;case 1:this.h[1]=b;this.o(this.F.frequency,b,c,l);break;case 2:this.h[2]=b;this.o(this.F.detune,b,c,l);break;case 3:this.h[3]=b;this.o(this.F.Q,b,c,l);break;case 4:this.h[4]=b,this.o(this.F.gain,b,c,l)}}};self.gf=class extends d{constructor(a,b,c,l){super(a);this.ba="delay";this.h=[b,c,l];this.m=
this.s();this.b=this.s();this.b.gain.value=l;this.a=this.s();this.a.gain.value=1-l;this.Tb=this.s();this.ea=this.c.createDelay(b);this.ea.delayTime.value=b;this.Kb=this.s();this.Kb.gain.value=c;this.m.connect(this.Tb);this.m.connect(this.a);this.Tb.connect(this.b);this.Tb.connect(this.ea);this.ea.connect(this.Kb);this.Kb.connect(this.Tb)}f(){this.m.disconnect();this.b.disconnect();this.a.disconnect();this.Tb.disconnect();this.ea.disconnect();this.Kb.disconnect();super.f()}ca(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}$(){return this.m}ka(a,b,c,l){const q=self.wa.ce;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.h[2]=b;this.o(this.b.gain,b,c,l);this.o(this.a.gain,1-b,c,l);break;case 4:this.h[1]=q(b);this.o(this.Kb.gain,q(b),c,l);break;case 5:this.h[0]=b,this.o(this.ea.delayTime,b,c,l)}}};self.ff=class extends d{constructor(a,b,c,l){super(a);this.ba="convolution";this.h=[c,l];this.He=this.Ge="";this.m=this.s();this.b=this.s();this.b.gain.value=l;this.a=
this.s();this.a.gain.value=1-l;this.Jb=this.c.createConvolver();this.Jb.normalize=c;this.Jb.buffer=b;this.m.connect(this.Jb);this.m.connect(this.a);this.Jb.connect(this.b)}f(){this.m.disconnect();this.Jb.disconnect();this.b.disconnect();this.a.disconnect();super.f()}ca(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}$(){return this.m}ka(a,b,c,l){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.h[1]=b,this.o(this.b.gain,b,c,l),this.o(this.a.gain,1-b,c,l)}}uh(a,b){this.Ge=
a;this.He=b}yb(){const a=super.yb();a.bufferOriginalUrl=this.Ge;a.bufferUrl="";a.bufferType=this.He;return a}};self.kf=class extends d{constructor(a,b,c,l,q,n){super(a);this.ba="flanger";this.h=[b,c,l,q,n];this.m=this.s();this.a=this.s();this.a.gain.value=1-n/2;this.b=this.s();this.b.gain.value=n/2;this.Mb=this.s();this.Mb.gain.value=q;this.ea=this.c.createDelay(b+c);this.ea.delayTime.value=b;this.C=this.c.createOscillator();this.C.frequency.value=l;this.R=this.s();this.R.gain.value=c;this.m.connect(this.ea);
this.m.connect(this.a);this.ea.connect(this.b);this.ea.connect(this.Mb);this.Mb.connect(this.ea);this.C.connect(this.R);this.R.connect(this.ea.delayTime);this.C.start(0)}f(){this.C.stop(0);this.m.disconnect();this.ea.disconnect();this.C.disconnect();this.R.disconnect();this.a.disconnect();this.b.disconnect();this.Mb.disconnect();super.f()}ca(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}$(){return this.m}ka(a,b,c,l){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);
this.h[4]=b;this.o(this.b.gain,b/2,c,l);this.o(this.a.gain,1-b/2,c,l);break;case 6:this.h[1]=b/1E3;this.o(this.R.gain,b/1E3,c,l);break;case 7:this.h[2]=b;this.o(this.C.frequency,b,c,l);break;case 8:this.h[3]=b/100,this.o(this.Mb.gain,b/100,c,l)}}};self.mf=class extends d{constructor(a,b,c,l,q,n,e){super(a);this.ba="phaser";this.h=[b,c,l,q,n,e];this.m=this.s();this.a=this.s();this.a.gain.value=1-e/2;this.b=this.s();this.b.gain.value=e/2;this.F=this.c.createBiquadFilter();this.F.type="allpass";this.F.frequency.value=
b;this.F.detune.value=c;this.F.Q.value=l;this.C=this.c.createOscillator();this.C.frequency.value=n;this.R=this.s();this.R.gain.value=q;this.m.connect(this.F);this.m.connect(this.a);this.F.connect(this.b);this.C.connect(this.R);this.R.connect(this.F.frequency);this.C.start(0)}f(){this.C.stop(0);this.m.disconnect();this.F.disconnect();this.C.disconnect();this.R.disconnect();this.a.disconnect();this.b.disconnect();super.f()}ca(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}$(){return this.m}ka(a,
b,c,l){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.h[5]=b;this.o(this.b.gain,b/2,c,l);this.o(this.a.gain,1-b/2,c,l);break;case 1:this.h[0]=b;this.o(this.F.frequency,b,c,l);break;case 2:this.h[1]=b;this.o(this.F.detune,b,c,l);break;case 3:this.h[2]=b;this.o(this.F.Q,b,c,l);break;case 6:this.h[3]=b;this.o(this.R.gain,b,c,l);break;case 7:this.h[4]=b,this.o(this.C.frequency,b,c,l)}}};self.lf=class extends d{constructor(a,b){super(a);this.ba="gain";this.h=[b];this.i=this.s();this.i.gain.value=
b}f(){this.i.disconnect();super.f()}ca(a){this.i.disconnect();this.i.connect(a)}$(){return this.i}ka(a,b,c,l){const q=self.wa.ce;switch(a){case 4:this.h[0]=q(b),this.o(this.i.gain,q(b),c,l)}}};self.pf=class extends d{constructor(a,b,c){super(a);this.ba="tremolo";this.h=[b,c];this.i=this.s();this.i.gain.value=1-c/2;this.C=this.c.createOscillator();this.C.frequency.value=b;this.R=this.s();this.R.gain.value=c/2;this.C.connect(this.R);this.R.connect(this.i.gain);this.C.start(0)}f(){this.C.stop(0);this.C.disconnect();
this.R.disconnect();this.i.disconnect();super.f()}ca(a){this.i.disconnect();this.i.connect(a)}$(){return this.i}ka(a,b,c,l){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.h[1]=b;this.o(this.i.gain,1-b/2,c,l);this.o(this.R.gain,b/2,c,l);break;case 7:this.h[0]=b,this.o(this.C.frequency,b,c,l)}}};self.nf=class extends d{constructor(a,b,c){super(a);this.ba="ringmod";this.h=[b,c];this.m=this.s();this.b=this.s();this.b.gain.value=c;this.a=this.s();this.a.gain.value=1-c;this.Zb=this.s();this.Zb.gain.value=
0;this.C=this.c.createOscillator();this.C.frequency.value=b;this.C.connect(this.Zb.gain);this.C.start(0);this.m.connect(this.Zb);this.m.connect(this.a);this.Zb.connect(this.b)}f(){this.C.stop(0);this.C.disconnect();this.Zb.disconnect();this.m.disconnect();this.b.disconnect();this.a.disconnect();super.f()}ca(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}$(){return this.m}ka(a,b,c,l){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.h[1]=b;this.o(this.b.gain,b,c,
l);this.o(this.a.gain,1-b,c,l);break;case 7:this.h[0]=b,this.o(this.C.frequency,b,c,l)}}};self.hf=class extends d{constructor(a,b,c,l,q,n){super(a);this.ba="distortion";this.h=[b,c,l,q,n];this.m=this.s();this.Mc=this.s();this.Lc=this.s();this.vh(l,q);this.b=this.s();this.b.gain.value=n;this.a=this.s();this.a.gain.value=1-n;this.Qc=this.c.createWaveShaper();this.Fd=new Float32Array(65536);this.yg(b,c);this.Qc.curve=this.Fd;this.m.connect(this.Mc);this.m.connect(this.a);this.Mc.connect(this.Qc);this.Qc.connect(this.Lc);
this.Lc.connect(this.b)}f(){this.m.disconnect();this.Mc.disconnect();this.Qc.disconnect();this.Lc.disconnect();this.b.disconnect();this.a.disconnect();super.f()}vh(a,b){.01>a&&(a=.01);this.Mc.gain.value=a;this.Lc.gain.value=Math.pow(1/a,.6)*b}yg(a,b){for(let c=0;32768>c;++c){let l=c/32768;l=this.Ih(l,a,b);this.Fd[32768+c]=l;this.Fd[32768-c-1]=-l}}Ih(a,b,c){c=1.05*c*b-b;const l=0>a?-a:a;return(l<b?l:b+c*self.wa.ei(l-b,1/c))*(0>a?-1:1)}ca(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}$(){return this.m}ka(a,b,c,l){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.h[4]=b,this.o(this.b.gain,b,c,l),this.o(this.a.gain,1-b,c,l)}}};self.ef=class extends d{constructor(a,b,c,l,q,n){super(a);this.ba="compressor";this.h=[b,c,l,q,n];this.i=this.c.createDynamicsCompressor();this.i.threshold.value=b;this.i.knee.value=c;this.i.ratio.value=l;this.i.attack.value=q;this.i.release.value=n}f(){this.i.disconnect();super.f()}ca(a){this.i.disconnect();this.i.connect(a)}$(){return this.i}ka(){}};
self.df=class extends d{constructor(a,b,c){super(a);this.ba="analyser";this.h=[b,c];this.i=this.c.createAnalyser();this.i.fftSize=b;this.i.smoothingTimeConstant=c;this.Ke=new Float32Array(this.i.frequencyBinCount);this.Xe=new Uint8Array(b);this.Ve=this.rb=0;this.j.eg(this)}f(){this.j.oh(this);this.i.disconnect();super.f()}ib(){this.i.getFloatFrequencyData(this.Ke);this.i.getByteTimeDomainData(this.Xe);const a=this.i.fftSize;let b=this.rb=0;for(var c=0;c<a;++c){let l=(this.Xe[c]-128)/128;0>l&&(l=-l);
this.rb<l&&(this.rb=l);b+=l*l}c=self.wa.Nf;this.rb=c(this.rb);this.Ve=c(Math.sqrt(b/a))}ca(a){this.i.disconnect();this.i.connect(a)}$(){return this.i}ka(){}Ef(){return{tag:this.na,index:this.Me,peak:this.rb,rms:this.Ve,binCount:this.i.frequencyBinCount,freqBins:this.Ke}}}}"use strict";
async function ba(d){if(!d.eb)try{d.eb=await navigator.wakeLock.request("screen"),d.eb.addEventListener("release",()=>{console.log("[Construct 3] Screen wake lock released");d.eb=null;B(d,"wake-lock-released")}),console.log("[Construct 3] Screen wake lock acquired"),B(d,"wake-lock-acquired")}catch(a){console.warn("[Construct 3] Failed to acquire screen wake lock: ",a),B(d,"wake-lock-error")}}
function Z(){var d=document.body;const a=d.style;a.setProperty("--temp-sai-top","env(safe-area-inset-top)");a.setProperty("--temp-sai-right","env(safe-area-inset-right)");a.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");a.setProperty("--temp-sai-left","env(safe-area-inset-left)");d=getComputedStyle(d);d=[d.getPropertyValue("--temp-sai-top"),d.getPropertyValue("--temp-sai-right"),d.getPropertyValue("--temp-sai-bottom"),d.getPropertyValue("--temp-sai-left")].map(b=>{b=parseInt(b,10);
return isFinite(b)?b:0});a.removeProperty("--temp-sai-top");a.removeProperty("--temp-sai-right");a.removeProperty("--temp-sai-bottom");a.removeProperty("--temp-sai-left");return d}
self.pa.Ta(class extends self.Ka{constructor(d){super(d,"platform-info");L(this,[["get-initial-state",()=>this.ud()],["request-wake-lock",()=>ba(this)],["release-wake-lock",()=>{this.eb&&(this.eb.release(),this.eb=null)}]]);window.addEventListener("resize",()=>{B(this,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:Z()})});this.eb=null}ud(){return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,
safeAreaInset:Z(),supportsWakeLock:!!navigator.wakeLock}}});
